import { useMemo, useState } from 'react'
import Icon from '../../components/Icon'

type ArtifactTab = 'Preview' | 'Metadata' | 'Versions' | 'Lineage' | 'Diff' | 'Integrity'

const artifactData = [
  { name: 'agenticos-command-center.png', type: 'Image', size: '2.8 MB', status: 'Ready', run: 'RUN-042', version: 'v4', updated: '2m ago' },
  { name: 'architecture-report.md', type: 'Document', size: '18 KB', status: 'Ready', run: 'RUN-041', version: 'v2', updated: '11m ago' },
  { name: 'provider-test.log', type: 'Log', size: '74 KB', status: 'Ready', run: 'RUN-041', version: 'v1', updated: '14m ago' },
  { name: 'implementation-plan.json', type: 'Structured', size: '12 KB', status: 'Draft', run: 'RUN-040', version: 'v3', updated: '32m ago' },
]

const previewLines = [
  'AgentiCOS frontend implementation plan',
  '',
  '01  inspect existing architecture',
  '02  build reversible frontend slice',
  '03  review changes',
  '04  run verification',
  '05  prepare evidence package',
]

export default function ArtifactViewer({ selected, onSelect, onAction }: { selected: string; onSelect: (name: string) => void; onAction: (message: string) => void }) {
  const [tab, setTab] = useState<ArtifactTab>('Preview')
  const current = useMemo(() => artifactData.find((artifact) => artifact.name === selected) ?? artifactData[0], [selected])

  return (
    <div className="artifact-viewer">
      <aside className="artifact-viewer__list">
        <div className="artifact-viewer__list-head"><span>Generated outputs</span><span className="count-pill">{artifactData.length}</span></div>
        <div className="artifact-viewer__list-body">
          {artifactData.map((artifact) => (
            <button key={artifact.name} type="button" className={current.name === artifact.name ? 'artifact-viewer__item artifact-viewer__item--active' : 'artifact-viewer__item'} onClick={() => onSelect(artifact.name)}>
              <span className="artifact-viewer__item-icon"><Icon name={artifact.type === 'Log' ? 'terminal' : artifact.type === 'Image' ? 'layout' : artifact.type === 'Structured' ? 'code' : 'archive'} size={14} /></span>
              <span><strong>{artifact.name}</strong><small>{artifact.type} · {artifact.size}</small></span>
              <span className={artifact.status === 'Ready' ? 'state-pill state-pill--completed' : 'state-pill state-pill--pending'}>{artifact.status}</span>
            </button>
          ))}
        </div>
      </aside>

      <div className="artifact-viewer__main">
        <div className="artifact-viewer__toolbar">
          <div><span className="eyebrow">{current.type}</span><h2>{current.name}</h2><small>{current.size} · generated by {current.run} · {current.version} · {current.updated}</small></div>
          <div className="studio-header__actions">
            <button className="icon-button" type="button" title="Copy artifact path" onClick={() => onAction('Artifact path copied')}><Icon name="copy" size={14} /></button>
            <button className="studio-button" type="button" onClick={() => onAction('Artifact download staged in preview')}><Icon name="arrow-down" size={13} /> Download</button>
            <button className="studio-button studio-button--active" type="button" onClick={() => onAction('Artifact handoff staged in preview')}><Icon name="send" size={13} /> Handoff</button>
          </div>
        </div>
        <div className="artifact-viewer__tabs" role="tablist" aria-label="Artifact views">
          {(['Preview', 'Metadata', 'Versions', 'Lineage'] as ArtifactTab[]).map((item) => <button type="button" key={item} role="tab" aria-selected={tab === item} className={tab === item ? 'artifact-viewer__tab artifact-viewer__tab--active' : 'artifact-viewer__tab'} onClick={() => setTab(item)}>{item}</button>)}
        </div>
        <div className="artifact-viewer__content">
          {tab === 'Preview' && (
            <div className={current.type === 'Image' ? 'artifact-rich-preview artifact-rich-preview--image' : 'artifact-rich-preview'}>
              <div className="artifact-rich-preview__icon"><Icon name={current.type === 'Image' ? 'layout' : 'archive'} size={30} /></div>
              {current.type === 'Document' || current.type === 'Structured' ? <pre>{previewLines.join('\n')}</pre> : <><strong>{current.name}</strong><span>{current.type} preview surface</span><small>Content rendering is provided by the future artifact runtime.</small></>}
            </div>
          )}
          {tab === 'Metadata' && <div className="artifact-meta-grid"><Metric label="Type" value={current.type} /><Metric label="Size" value={current.size} /><Metric label="Run" value={current.run} /><Metric label="Version" value={current.version} /><Metric label="Status" value={current.status} /><Metric label="Updated" value={current.updated} /><Metric label="Checksum" value="sha256 · preview" /><Metric label="Source" value="Agent workspace" /></div>}
          {tab === 'Versions' && <div className="artifact-version-list">{['v4 · current · 2m ago','v3 · previous · 12m ago','v2 · archived · 31m ago'].map((version, index) => <button key={version} type="button" onClick={() => onAction('Artifact ' + version.split(' · ')[0] + ' opened in preview')}><span>{version.split(' · ')[0]}</span><div><strong>{version.split(' · ')[1]}</strong><small>{version.split(' · ')[2]}</small></div><Icon name={index === 0 ? 'check' : 'chevron-right'} size={13} /></button>)}</div>}
          {tab === 'Diff' && <div className="artifact-diff"><div><span className="eyebrow">Version comparison</span><strong>{current.version} → previous</strong><small>12 changed lines · 2 metadata changes · no secret material</small></div><pre>{'+ added evidence reference\n- draft-only status\n+ verified handoff marker'}</pre><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('Artifact diff review opened in preview')}>Review diff</button></div>}
          {tab === 'Integrity' && <div className="artifact-integrity"><div><span>Checksum</span><strong>sha256 · verified preview</strong></div><div><span>Source run</span><strong>{current.run}</strong></div><div><span>Provenance</span><strong>Run → Agent step → Artifact → Delivery</strong></div><div><span>Policy</span><strong>Workspace-scoped</strong></div><div><span>Retention</span><strong>30 days · preview</strong></div><div><span>Trust</span><strong>Pending runtime attestation</strong></div></div>}
          {tab === 'Lineage' && <div className="artifact-lineage"><div><span>Source run</span><strong>{current.run}</strong></div><div className="lineage-arrow">→</div><div><span>Agent step</span><strong>Prepare handoff</strong></div><div className="lineage-arrow">→</div><div><span>Artifact</span><strong>{current.version}</strong></div><div className="lineage-arrow">→</div><div><span>Delivery</span><strong>Ready for handoff</strong></div></div>}
        </div>
      </div>
    </div>
  )
}

function Metric({ label, value }: { label: string; value: string }) {
  return <div className="platform-metric-card"><span>{label}</span><strong>{value}</strong></div>
}
