import { useState, type ReactNode } from 'react'
import Icon from '../../components/Icon'

type Env={id:string;name:string;type:'Local'|'Container'|'Remote';status:'Ready'|'Preview'|'Draft';base:string;runtime:string;network:'Isolated'|'Allowlist'|'Open';cpu:number;memory:number;disk:number;image:string;setup:string;workdir:string;autoCleanup:boolean}
const seed:Env[]=[
 {id:'local',name:'Local Desktop',type:'Local',status:'Ready',base:'Workstation',runtime:'Rust stable · Node 22',network:'Allowlist',cpu:8,memory:16,disk:80,image:'Native host',setup:'pnpm install && cargo check',workdir:'/workspace',autoCleanup:false},
 {id:'linux-builder',name:'Linux Builder',type:'Container',status:'Preview',base:'Ubuntu 24.04',runtime:'Rust stable · Node 22',network:'Isolated',cpu:6,memory:12,disk:40,image:'agenticos/builder:latest',setup:'toolchain bootstrap',workdir:'/workspace',autoCleanup:true},
 {id:'agent-vm',name:'Agent VM',type:'Remote',status:'Preview',base:'Ubuntu',runtime:'Rust stable · Node 22',network:'Isolated',cpu:8,memory:16,disk:100,image:'snapshot:agenticos',setup:'restore snapshot',workdir:'/workspace',autoCleanup:true},
]
export default function EnvironmentBuilder({onAction}:{onAction:(message:string)=>void}){
 const [items,setItems]=useState(seed);const [selectedId,setSelectedId]=useState(seed[0].id);const [tab,setTab]=useState<'Overview'|'Runtime'|'Network'|'Lifecycle'>('Overview')
 const current=items.find(i=>i.id===selectedId)??items[0]
 const patch=(value:Partial<Env>)=>setItems(list=>list.map(item=>item.id===current.id?{...item,...value}:item))
 const create=()=>{const id='env-'+Date.now();const next:Env={...seed[1],id,name:'New environment',status:'Draft',image:'custom image',setup:'Define setup script'};setItems(list=>[next,...list]);setSelectedId(id);setTab('Overview');onAction('New environment created in preview')}
 return <div className="environment-builder">
  <aside className="environment-builder__rail"><div className="environment-builder__rail-head"><div><span className="eyebrow">Runtime environments</span><strong>Environments</strong></div><button className="icon-button" type="button" aria-label="Create environment" title="Create environment" onClick={create}><Icon name="plus" size={15}/></button></div><div className="environment-builder__list">{items.map(item=><button type="button" key={item.id} className={item.id===current.id?'environment-builder__item environment-builder__item--active':'environment-builder__item'} onClick={()=>setSelectedId(item.id)}><span className="environment-builder__icon"><Icon name={item.type==='Local'?'layout':item.type==='Container'?'layers':'cloud'} size={14}/></span><span><strong>{item.name}</strong><small>{item.type} · {item.runtime}</small></span><span className={item.status==='Ready'?'status-dot status-dot--live':'status-dot status-dot--offline'}/></button>)}</div><div className="environment-builder__rail-foot"><span className="mono-text">{items.length} environments</span><span className="state-pill state-pill--pending">Runtime-owned</span></div></aside>
  <section className="environment-builder__workspace"><header className="environment-builder__header"><div><span className="eyebrow">{current.status} · {current.type}</span><h2>{current.name}</h2><p>{current.base} · {current.runtime}</p></div><div className="environment-builder__actions"><button className="studio-button" type="button" onClick={()=>onAction(current.name+' validation staged in preview')}><Icon name="check-circle" size={13}/> Validate</button><button className="studio-button studio-button--active" type="button" onClick={()=>onAction(current.name+' save staged in preview')}><Icon name="check" size={13}/> Save</button></div></header>
  <nav className="environment-builder__tabs" role="tablist" aria-label="Environment builder">{(['Overview','Runtime','Network','Lifecycle'] as const).map(item=><button type="button" key={item} role="tab" aria-selected={tab===item} className={tab===item?'environment-builder__tab environment-builder__tab--active':'environment-builder__tab'} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  <div className="environment-builder__content">
   {tab==='Overview'&&<Section title="Environment identity" description="Define the reproducible runtime envelope used by local, background or future remote agents."><div className="environment-builder__grid environment-builder__grid--2"><Field label="Name"><input value={current.name} onChange={e=>patch({name:e.target.value})}/></Field><Field label="Base image"><input value={current.image} onChange={e=>patch({image:e.target.value})}/></Field><Field label="Working directory"><input value={current.workdir} onChange={e=>patch({workdir:e.target.value})}/></Field><Field label="Setup command"><input value={current.setup} onChange={e=>patch({setup:e.target.value})}/></Field></div><div className="environment-builder__stat-grid"><Stat label="Type" value={current.type}/><Stat label="Status" value={current.status}/><Stat label="Network" value={current.network}/><Stat label="Auto cleanup" value={current.autoCleanup?'Enabled':'Disabled'}/></div></Section>}
   {tab==='Runtime'&&<Section title="Runtime capacity" description="Preview bounded resource envelopes. Physical allocation is enforced outside the UI."><Range label="CPU cores" value={current.cpu} min={1} max={32} suffix={String(current.cpu)} onChange={value=>patch({cpu:value})}/><Range label="Memory GB" value={current.memory} min={2} max={64} suffix={String(current.memory)+' GB'} onChange={value=>patch({memory:value})}/><Range label="Disk GB" value={current.disk} min={10} max={500} suffix={String(current.disk)+' GB'} onChange={value=>patch({disk:value})}/><div className="environment-builder__capacity"><div><span>CPU</span><strong>{current.cpu} cores</strong></div><div><span>Memory</span><strong>{current.memory} GB</strong></div><div><span>Disk</span><strong>{current.disk} GB</strong></div></div></Section>}
   {tab==='Network'&&<Section title="Network & secrets" description="Keep network access and secret exposure explicit before an environment can run an agent."><Field label="Network policy"><Select value={current.network} options={['Isolated','Allowlist','Open']} onChange={value=>patch({network:value as Env['network']})}/></Field><Toggle label="External secrets mounted at runtime" value={true} onChange={()=>onAction('Secret mount preference staged in preview')}/><Toggle label="MCP access" value={true} onChange={()=>onAction('MCP access preference staged in preview')}/><div className="callout"><Icon name="shield" size={14}/><span>Secrets are never rendered by this component. Runtime identity, mounts and network enforcement remain outside presentation state.</span></div></Section>}
   {tab==='Lifecycle'&&<Section title="Lifecycle & cleanup" description="Control initialization, health checks, retention and cleanup expectations."><Toggle label="Auto cleanup after run" value={current.autoCleanup} onChange={value=>patch({autoCleanup:value})}/><Toggle label="Health check before attach" value={true} onChange={()=>onAction('Health check preference staged in preview')}/><Toggle label="Keep failed environments" value={false} onChange={()=>onAction('Failure retention preference staged in preview')}/><div className="environment-builder__lifecycle"><div><span>Prepare</span><strong>Image → setup → health</strong></div><Icon name="chevron-right" size={14}/><div><span>Attach</span><strong>Workspace → agent</strong></div><Icon name="chevron-right" size={14}/><div><span>Release</span><strong>Artifacts → cleanup</strong></div></div></Section>}
  </div></section>
 </div>
}
function Section({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="environment-builder__section"><header><span className="eyebrow">Environment configuration</span><h3>{title}</h3><p>{description}</p></header><div className="environment-builder__section-body">{children}</div></section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="environment-builder__field"><span>{label}</span>{children}</label>}
function Select({value,options,onChange}:{value:string;options:string[];onChange:(value:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select>}
function Range({label,value,min,max,suffix,onChange}:{label:string;value:number;min:number;max:number;suffix:string;onChange:(value:number)=>void}){return <label className="environment-builder__range"><span><span>{label}</span><strong>{suffix}</strong></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){return <button type="button" className={value?'environment-builder__toggle environment-builder__toggle--active':'environment-builder__toggle'} aria-pressed={value} onClick={()=>onChange(!value)}><span><strong>{label}</strong><small>{value?'Enabled':'Disabled'}</small></span><span className="switch"><span/></span></button>}
function Stat({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}