import { useMemo, useState } from 'react'
import Icon from '../../components/Icon'
import { MetricCard, Panel, Tag } from './PlatformPrimitives'

type LaneState='ready'|'running'|'complete'|'blocked'
type Candidate=[string,string,string,string,LaneState,string]
const candidates:Candidate[]=[
 ['lane-a','Builder','Qwen3 Coder','Worktree A','complete','92'],
 ['lane-b','Builder','GPT-5.3-Codex','Worktree B','running','—'],
 ['lane-c','Architect','Claude Sonnet 4.5','Worktree C','complete','89'],
 ['lane-d','Reviewer','Gemini 3 Pro','Read-only','blocked','—'],
]
const criteria=[['Correctness','Tests + type checks'],['Safety','Policy + permissions'],['Scope','Task boundaries'],['UX','Visual interaction'],['Evidence','Artifacts + logs']]

export function AgentArena({onAction}:{onAction:(message:string)=>void}){
 const [selected,setSelected]=useState(candidates[0][0]),[running,setRunning]=useState(false),[judging,setJudging]=useState(false),[criterion,setCriterion]=useState(criteria[0][0])
 const active=useMemo(()=>candidates.find(c=>c[0]===selected)??candidates[0],[selected])
 const act=(m:string)=>onAction(m+' staged in preview')
 return <div className="agent-arena">
  <header className="agent-arena__hero"><div><span className="eyebrow">Parallel evaluation</span><h1>Agent Arena</h1><p>Run the same mission through isolated agent lanes, compare plans and evidence, then converge without contaminating the primary workspace.</p></div><div className="agent-arena__actions"><Tag label="Isolated lanes"/><button className={running?'studio-button studio-button--active':'studio-button'} type="button" onClick={()=>setRunning(v=>!v)}><Icon name="play" size={13}/>{running?'Arena running':'Start arena'}</button><button className="studio-button studio-button--active" type="button" onClick={()=>{setJudging(true);act('Multi-agent judge')}}><Icon name="check" size={13}/>{judging?'Judge armed':'Judge candidates'}</button></div></header>
  <div className="platform-metrics"><MetricCard label="Candidates" value="4" sub="3 isolated · 1 read-only"/><MetricCard label="Worktrees" value="3" sub="Parallel-safe state"/><MetricCard label="Evidence" value="12" sub="Artifacts + checks"/><MetricCard label="Judge" value={judging?'Armed':'Idle'} sub="Criterion-based comparison"/></div>
  <Panel title="Mission"><div className="arena-mission"><div><span className="eyebrow">Shared prompt</span><strong>Implement provider routing with fail-closed verification.</strong><p>Every lane receives the same objective and baseline context. Candidate-specific changes stay isolated.</p></div><div className="arena-mission__facts"><div><span>Context</span><strong>46.2k</strong></div><div><span>Budget</span><strong>48 tool turns</strong></div><div><span>Isolation</span><strong>Git worktrees</strong></div></div></div></Panel>
  <div className="agent-arena__layout"><Panel title="Candidate lanes"><div className="arena-lanes">{candidates.map(c=><button key={c[0]} type="button" className={selected===c[0]?'arena-lane arena-lane--active':'arena-lane'} onClick={()=>setSelected(c[0])}><span className={'arena-lane__state arena-lane__state--'+c[4]}><Icon name={c[4]==='complete'?'check':c[4]==='blocked'?'lock':c[4]==='running'?'activity':'clock'} size={12}/></span><span><strong>{c[1]} · {c[0]}</strong><small>{c[2]} · {c[3]}</small></span><b>{c[5]}</b></button>)}</div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>act('Add candidate')}>Add lane</button><button className="studio-button" type="button" onClick={()=>act('Open worktree map')}>Worktrees</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Stop arena')}>Stop arena</button></div></Panel>
   <Panel title={active[0]}><div className="arena-candidate-head"><div><span className="eyebrow">{active[1]}</span><h2>{active[2]}</h2><p>{active[3]} · state: {active[4]}</p></div><Tag label={active[5]==='—'?'Pending':'Scored '+active[5]}/></div><div className="arena-criteria">{criteria.map(([name,detail],i)=><button type="button" className={criterion===name?'arena-criterion arena-criterion--active':'arena-criterion'} key={name} onClick={()=>setCriterion(name)}><span>{name}</span><strong>{active[5]==='—'?'—':i===0?active[5]+'%':i===1?'96%':i===2?'94%':i===3?'91%':'88%'}</strong><small>{detail}</small></button>)}</div><div className="arena-evidence"><div><span>Plan</span><strong>3 steps · 8.2k context</strong></div><div><span>Changed files</span><strong>7 files · +124 −32</strong></div><div><span>Checks</span><strong>14 / 16 passed</strong></div><div><span>Artifacts</span><strong>4 attached</strong></div></div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>act('Open candidate diff')}>Diff</button><button className="studio-button" type="button" onClick={()=>act('Open candidate artifacts')}>Evidence</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Converge candidate into review')}>Converge</button></div></Panel></div>
  <Panel title="Convergence"><div className="arena-convergence"><div><span className="eyebrow">Decision package</span><h3>{criterion} comparison</h3><p>Compare the selected criterion across lanes before producing a merged recommendation package.</p></div><div className="arena-convergence__scores">{candidates.map(c=><div key={c[0]}><span>{c[0]}</span><strong>{c[5]}</strong></div>)}</div></div><div className="arena-guard"><Icon name="shield" size={13}/><span>No candidate is written into main by the arena. Convergence remains a review intent until the runtime/worktree service is connected.</span></div></Panel>
 </div>
}