import { useMemo, useState } from 'react'
import Icon from '../../components/Icon'
import { MetricCard, Panel, Tag } from './PlatformPrimitives'

type ReviewState='Open'|'Resolved'|'Blocked'
const threads:Array<[string,string,string,string,ReviewState,string]>=[
 ['R-118','Provider routing fallback can cross policy boundary','navigation.ts:191','Reviewer','Open','High'],
 ['R-117','Need explicit keyboard focus restore after command palette closes','CommandPalette.tsx:92','QA','Open','Medium'],
 ['R-116','Evidence copy should distinguish preview from verified artifacts','EvidenceArtifactInspector.tsx:74','Reviewer','Resolved','Low'],
 ['R-115','Checkpoint should be linked from release gate','RunControlCenter.tsx:118','Release','Blocked','Medium'],
]
const checks=[['Type safety','Navigation registry + PlatformMode consistency','Pass'],['Scope','Changed files match task scope','Pass'],['Tests','Targeted test evidence attached','Pending'],['Accessibility','Keyboard + responsive evidence','Pending'],['Policy','Destructive operations remain gated','Pass']]

export function CollaborationReviewCenter({onAction}:{onAction:(message:string)=>void}){
 const [selected,setSelected]=useState(threads[0][0]),[state,setState]=useState<ReviewState>('Open'),[tab,setTab]=useState<'threads'|'checks'|'approval'>('threads'),[search,setSearch]=useState('')
 const [resolution,setResolution]=useState<'Addressed'|'Won\'t fix'|'Incorrect'>('Addressed')
 const [selectedFindings,setSelectedFindings]=useState<string[]>([])
 const [reviewNewOnly,setReviewNewOnly]=useState(true)
 const current=threads.find(t=>t[0]===selected)??threads[0]
 const visible=useMemo(()=>threads.filter(t=>t.join(' ').toLowerCase().includes(search.toLowerCase())),[search])
 const act=(m:string)=>onAction(m+' staged in preview')
 return <div className="collab-review"><header className="collab-review__hero"><div><span className="eyebrow">Engineering collaboration</span><h1>Collaboration & Review Center</h1><p>Bring diff threads, automated findings, approvals, verification checks and reviewer handoffs into one collaboration surface.</p></div><div className="collab-review__actions"><Tag label="Preview"/><button className="studio-button" type="button" onClick={()=>act('Request reviewer')}>Request review</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Generate review summary')}><Icon name="spark" size={13}/>Review summary</button></div></header>
 <div className="platform-metrics"><MetricCard label="Threads" value="4" sub="2 open · 1 resolved · 1 blocked"/><MetricCard label="Findings" value="12" sub="3 high-impact"/><MetricCard label="Checks" value="3/5" sub="Release evidence pending"/><MetricCard label="Approvals" value="1" sub="Release gate"/></div>
 <div className="collab-review__tabs">{(['threads','checks','approval'] as const).map(t=><button type="button" key={t} className={tab===t?'knowledge-tab knowledge-tab--active':'knowledge-tab'} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='threads'&&<div className="collab-review__layout"><Panel title="Review threads"><div className="collab-search"><Icon name="search" size={12}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search findings…" aria-label="Search findings"/></div><div className="collab-threads">{visible.map(t=><button type="button" key={t[0]} className={selected===t[0]?'collab-thread collab-thread--active':'collab-thread'} onClick={()=>setSelected(t[0])}><span className={'collab-thread__priority collab-thread__priority--'+t[5].toLowerCase()}>{t[5][0]}</span><span><strong>{t[0]} · {t[1]}</strong><small>{t[2]} · {t[3]}</small></span><Tag label={t[4]}/></button>)}</div></Panel>
 <Panel title={current[0]}><div className="collab-detail-head"><div><span className="eyebrow">{current[3]} · {current[5]} priority</span><h2>{current[1]}</h2><p>{current[2]}</p></div><span className="state-pill state-pill--pending">{state}</span></div><div className="collab-comment"><span className="eyebrow">Review comment</span><p>Show the exact policy path, affected scope and evidence needed before this finding can be considered resolved.</p></div><div className="collab-evidence-grid"><div><span>Scope</span><strong>Frontend + runtime contract</strong></div><div><span>Evidence</span><strong>Diff + targeted check</strong></div><div><span>Owner</span><strong>{current[3]}</strong></div><div><span>Next gate</span><strong>{current[4]==='Blocked'?'Unblock verification':'Review'}</strong></div></div><div className="collab-resolution">
  <span className="eyebrow">Resolution reason</span>
  <div>{(['Addressed',"Won't fix",'Incorrect'] as const).map((reason)=><button key={reason} type="button" className={resolution===reason ? 'studio-button studio-button--active' : 'studio-button'} onClick={()=>setResolution(reason)}>{reason}</button>)}</div>
</div>
<div className="platform-actions"><button className="studio-button" type="button" onClick={()=>act('Open threaded discussion')}>Thread</button><button className="studio-button" type="button" onClick={()=>act('Open affected diff')}>Diff</button><button className="studio-button" type="button" onClick={()=>setState(state==='Resolved'?'Open':'Resolved')}>{state==='Resolved'?'Reopen':'Resolve'}</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Request re-review')}>Re-review</button></div></Panel>
 <div className="collab-review__batchbar">
  <div><span className="eyebrow">Batch review</span><strong>{selectedFindings.length || 1} finding{(selectedFindings.length || 1) === 1 ? '' : 's'} selected</strong><small>{reviewNewOnly ? 'Only new findings since last review' : 'All findings in current review'}</small></div>
  <div><button className={reviewNewOnly ? 'studio-button studio-button--active' : 'studio-button'} type="button" aria-pressed={reviewNewOnly} onClick={()=>setReviewNewOnly((value)=>!value)}>New only</button><button className="studio-button" type="button" onClick={()=>setSelectedFindings(visible.slice(0,3).map(item=>item[0]))}>Select batch</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Fix batch with agent')}>Fix batch</button></div>
 </div>
 </div>}
 {tab==='checks'&&<Panel title="Review & release checks"><div className="review-checks">{checks.map(c=><div key={c[0]}><span className="review-check-icon"><Icon name={c[2]==='Pass'?'check':'clock'} size={11}/></span><span><strong>{c[0]}</strong><small>{c[1]}</small></span><Tag label={c[2]}/></div>)}</div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>act('Refresh checks')}>Refresh</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Generate evidence bundle')}>Evidence bundle</button></div></Panel>}
 {tab==='approval'&&<Panel title="Approval gate"><div className="approval-gate-card"><Icon name="shield" size={22}/><div><span className="eyebrow">Release mutation</span><h2>APP-024</h2><p>Publishing this review candidate would change protected release state.</p></div><Tag label="Human approval"/></div><div className="collab-gate-facts"><div><span>Scope</span><strong>release branch only</strong></div><div><span>Risk</span><strong>High</strong></div><div><span>Rollback</span><strong>Checkpoint #17</strong></div><div><span>Evidence</span><strong>3/5 checks</strong></div></div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>act('Reject approval')}>Reject</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Approve release gate')}>Approve</button></div></Panel>}
 <div className="collab-review__footer"><span><Icon name="shield" size={12}/> Review decisions do not mutate Git or release state in preview mode.</span><span>Comments, approvals and checks become persistent through runtime services.</span></div>
 </div>
}