import { useState } from 'react'
import Icon from '../../components/Icon'
import { MetricCard, Panel, Tag } from './PlatformPrimitives'

const components=[['Button','Primary, secondary, danger, disabled'],['Input','Default, focus, error, disabled'],['Panel','Default, dense, elevated'],['Status','Active, pending, failed, offline'],['Tabs','Default, selected, keyboard focus'],['Toast','Info, success, warning, error']]
const tokens=[['Spacing','4 · 8 · 12 · 16 · 24 · 32'],['Radius','6 · 8 · 10 · 14'],['Type','12 · 14 · 16 · 18 · 24 · 32'],['Density','Compact · Balanced · Comfortable']]
export function DesignSystemStudio({onAction}:{onAction:(message:string)=>void}){
 const [selected,setSelected]=useState('Button'),[density,setDensity]=useState('Balanced'),[focus,setFocus]=useState(false),[disabled,setDisabled]=useState(false)
 const component=components.find(c=>c[0]===selected)??components[0]
 return <div className="design-system"><header className="design-system__hero"><div><span className="eyebrow">Frontend foundations</span><h1>Design System Studio</h1><p>Inspect reusable components, interaction states, typography, spacing and density so every AgentiCOS surface shares the same visual contract.</p></div><div className="design-system__actions"><Tag label="System surface"/><button className="studio-button" type="button" onClick={()=>setFocus(v=>!v)}>Focus states</button><button className={disabled?'studio-button studio-button--active':'studio-button'} type="button" onClick={()=>setDisabled(v=>!v)}>Disabled states</button></div></header>
 <div className="platform-metrics"><MetricCard label="Components" value="6" sub="Core interactive primitives"/><MetricCard label="Tokens" value="4 sets" sub="Spacing, radius, type, density"/><MetricCard label="States" value="24+" sub="Interaction variants"/><MetricCard label="Consistency" value="Governed" sub="Single visual contract"/></div>
 <div className="design-system__layout"><Panel title="Component catalog"><div className="component-list">{components.map(c=><button type="button" key={c[0]} className={selected===c[0]?'component-row component-row--active':'component-row'} onClick={()=>setSelected(c[0])}><Icon name={c[0]==='Status'?'activity':c[0]==='Panel'?'layout':c[0]==='Tabs'?'layers':c[0]==='Toast'?'bell':'code'} size={13}/><span><strong>{c[0]}</strong><small>{c[1]}</small></span><Icon name="chevron-right" size={12}/></button>)}</div></Panel>
 <Panel title={component[0]}><div className="component-demo"><span className="eyebrow">{component[1]}</span><div className="component-preview"><button disabled={disabled} className={focus?'studio-button studio-button--active':'studio-button'} type="button" onClick={()=>onAction(component[0]+' interaction staged in preview')}>Primary action</button><button className="studio-button" type="button">Secondary</button><input className="design-input" placeholder="Input preview" aria-label="Input preview"/><Tag label="Status"/></div></div><div className="design-states"><span>States</span><div><Tag label="default"/><Tag label="hover"/><Tag label="focus"/><Tag label="disabled"/><Tag label="loading"/><Tag label="error"/></div></div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>onAction('Open component source in preview')}>Source</button><button className="studio-button" type="button" onClick={()=>onAction('Copy component token contract')}>Copy contract</button><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('Add component variant in preview')}>Add variant</button></div></Panel></div>
 <div className="design-system__token-grid">{tokens.map(t=><Panel title={t[0]} key={t[0]}><strong>{t[1]}</strong>{t[0]==='Density'&&<div className="design-density">{['Compact','Balanced','Comfortable'].map(v=><button key={v} type="button" className={density===v?'studio-button studio-button--active':'studio-button'} onClick={()=>setDensity(v)}>{v}</button>)}</div>}</Panel>)}</div>
 <Panel title="Accessibility contract"><div className="design-a11y"><div><Icon name="check-circle" size={13}/><span>Visible keyboard focus</span><strong>{focus?'Enabled':'Configured'}</strong></div><div><Icon name="check-circle" size={13}/><span>Disabled affordance</span><strong>{disabled?'Preview':'Configured'}</strong></div><div><Icon name="check-circle" size={13}/><span>Reduced motion</span><strong>Supported by QA lab</strong></div><div><Icon name="check-circle" size={13}/><span>Semantic controls</span><strong>Button / input / tab patterns</strong></div></div><div className="design-system__guard"><Icon name="shield" size={12}/><span>Component states are presentation contracts; runtime data and actions are supplied by feature adapters.</span></div></Panel>
 </div>
}