import { useMemo, useState } from 'react'
import Icon from '../../components/Icon'
import { MetricCard, Panel, Tag } from './PlatformPrimitives'

type EnvironmentKind='Local'|'Worktree'|'Cloud'|'SSH'
const envs:Array<[string,EnvironmentKind,string,string,string]>=[
 ['Local Desktop','Local','Tauri workstation','Rust stable · Node 22','Ready'],
 ['Mission Worktree','Worktree','Isolated Git checkout','Same dependencies · snapshot','Ready'],
 ['Cloud Agent VM','Cloud','Ephemeral remote VM','Ubuntu · cached toolchain','Preview'],
 ['Remote SSH','SSH','User-managed host','SSH transport · policy gated','Preview'],
]
export function EnvironmentLab({onAction}:{onAction:(message:string)=>void}){
 const [selected,setSelected]=useState(envs[0][0]),[network,setNetwork]=useState<'off'|'restricted'|'open'>('restricted'),[snapshot,setSnapshot]=useState(true)
 const [previewPort,setPreviewPort]=useState(5173)
 const [previewEnabled,setPreviewEnabled]=useState(true)
 const current=useMemo(()=>envs.find(e=>e[0]===selected)??envs[0],[selected])
 const act=(m:string)=>onAction(m+' staged in preview')
 return <div className="environment-lab">
  <header className="environment-lab__hero"><div><span className="eyebrow">Runtime environments</span><h1>Environment Lab</h1><p>Define the machine, isolation, network, setup and snapshot policy used by an agent mission.</p></div><div className="environment-lab__actions"><Tag label="Policy-gated"/><button className="studio-button" type="button" onClick={()=>act('Create environment')}>New environment</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Run environment preflight')}><Icon name="check-circle" size={13}/> Preflight</button></div></header>
  <div className="platform-metrics"><MetricCard label="Environments" value="4" sub="1 local · 1 worktree · 1 cloud · 1 SSH"/><MetricCard label="Network" value={network} sub="Runtime policy"/><MetricCard label="Snapshots" value={snapshot?'Enabled':'Disabled'} sub="Point-in-time restore"/><MetricCard label="Secrets" value="External" sub="Never shown to UI"/></div>
  <div className="environment-lab__grid"><Panel title="Environment targets"><div className="environment-targets">{envs.map(([name,kind,detail,stack,state])=><button type="button" key={name} className={selected===name?'environment-card environment-card--active':'environment-card'} onClick={()=>setSelected(name)}><div><Icon name={kind==='Local'?'home':kind==='Worktree'?'branch':kind==='Cloud'?'cloud':'network'} size={16}/><strong>{name}</strong></div><small>{detail}</small><span>{stack}</span><Tag label={state}/></button>)}</div></Panel>
   <Panel title={current[0]}><div className="environment-preview">
      <div><span className="eyebrow">Live preview</span><strong>{previewEnabled ? 'Browser tunnel ready' : 'Preview disabled'}</strong><small>Port-forwarded UI preview for agent verification.</small></div>
      <div className="environment-preview__controls"><label>Port<input type="number" min={1} max={65535} value={previewPort} onChange={(event)=>setPreviewPort(Math.max(1, Math.min(65535, Number(event.target.value) || 1)))}/></label><button type="button" className={previewEnabled ? 'studio-button studio-button--active' : 'studio-button'} aria-pressed={previewEnabled} onClick={()=>setPreviewEnabled((value)=>!value)}>{previewEnabled ? 'Preview on' : 'Preview off'}</button><button type="button" className="studio-button" onClick={()=>act('Open live preview on port '+previewPort)}>Open preview</button></div>
    </div><div className="environment-detail"><div><span>Type</span><strong>{current[1]}</strong></div><div><span>Setup</span><strong>Environment contract selected</strong></div><div><span>Isolation</span><strong>{current[1]==='Local'?'Current workspace':current[1]==='Worktree'?'Git worktree':'Process / VM boundary'}</strong></div><div><span>Persistence</span><strong>{snapshot?'Snapshot before high-impact changes':'Ephemeral'}</strong></div></div><div className="environment-section"><span className="eyebrow">Network policy</span><div className="environment-options">{(['off','restricted','open'] as const).map(value=><button type="button" key={value} className={network===value?'studio-button studio-button--active':'studio-button'} onClick={()=>setNetwork(value)}>{value}</button>)}</div></div><div className="environment-section"><span className="eyebrow">Runtime setup</span><div className="environment-checks">{['Repository checkout','Dependencies ready','Environment variables attached externally','Verification commands defined','Artifact directory available'].map((item,index)=><div key={item}><Icon name="check" size={12}/><span>{item}</span><small>{index===2?'secret-safe':'configured'}</small></div>)}</div></div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>setSnapshot(v=>!v)}>{snapshot?'Disable snapshots':'Enable snapshots'}</button><button className="studio-button" type="button" onClick={()=>act('Open environment configuration')}>Configure</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Resume environment')}>Resume</button></div></Panel></div>
  <Panel title="Lifecycle"><div className="environment-lifecycle">{['Create','Setup','Preflight','Run','Snapshot','Resume','Destroy'].map((step,index)=><div key={step} className={index<4?'environment-step environment-step--done':'environment-step'}><span>{index<4?'✓':index+1}</span><strong>{step}</strong></div>)}</div><div className="environment-boundary"><Icon name="shield" size={13}/><span>Environment creation, SSH connection, network changes, secrets attachment and destruction require runtime authorization. The UI only stages these intents.</span></div></Panel>
 </div>
}