import { useMemo, useState } from 'react'
import Icon from '../../components/Icon'
import { navigationItems, platformModes, primaryRailIds, type RailMode } from '../../navigation'
import { MetricCard, Panel, Tag } from './PlatformPrimitives'

const studioOwned = new Set<RailMode>(['files','terminal','runs','agents','artifacts','settings'])
const appOwned = new Set<RailMode>(['chat'])
const categoryLabel: Record<string,string> = { build:'Build', operate:'Operate', configure:'Configure', integrate:'Integrate' }

export function FrontendCoverageStudio({onAction}:{onAction:(message:string)=>void}){
 const [query,setQuery]=useState(''),[owner,setOwner]=useState<'all'|'platform'|'studio'|'app'>('all'),[selected,setSelected]=useState<RailMode>('overview')
 const filtered=useMemo(()=>navigationItems.filter(item=>(owner==='all'||(owner==='platform'&&!studioOwned.has(item.id)&&!appOwned.has(item.id))||(owner==='studio'&&studioOwned.has(item.id))||(owner==='app'&&appOwned.has(item.id)))&&item.id+' '+item.label+' '+item.detail).filter(item=>(item.id+' '+item.label+' '+item.detail).toLowerCase().includes(query.toLowerCase())),[query,owner])
 const active=navigationItems.find(item=>item.id===selected)??navigationItems[0]
 const ownerOf=(id:RailMode)=>appOwned.has(id)?'App shell':studioOwned.has(id)?'StudioSurface':'PlatformSurface'
 const dedicated=navigationItems.filter(i=>ownerOf(i.id)==='PlatformSurface').length
 const studio=studioOwned.size, app=appOwned.size
 return <div className="coverage-studio"><header className="coverage-studio__hero"><div><span className="eyebrow">Frontend architecture inventory</span><h1>Frontend Coverage Studio</h1><p>Auditable inventory of every navigation surface, its UI owner, capability group and primary-rail exposure. This is the control board for presentation completeness.</p></div><div className="coverage-studio__actions"><Tag label="Source of truth: navigation.ts"/><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('Coverage report export staged in preview')}><Icon name="download" size={13}/>Export report</button></div></header>
 <div className="platform-metrics"><MetricCard label="Navigation surfaces" value={String(navigationItems.length)} sub="Registry entries"/><MetricCard label="Platform surfaces" value={String(dedicated)} sub="Dedicated feature routing"/><MetricCard label="Studio legacy" value={String(studio)} sub="Explicitly owned by StudioSurface"/><MetricCard label="App shell" value={String(app)} sub="Chat + shell ownership"/></div>
 <div className="coverage-studio__toolbar"><div className="coverage-search"><Icon name="search" size={12}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search surfaces…" aria-label="Search frontend surfaces"/></div>{(['all','platform','studio','app'] as const).map(item=><button type="button" key={item} className={owner===item?'studio-button studio-button--active':'studio-button'} onClick={()=>setOwner(item)}>{item}</button>)}</div>
 <div className="coverage-studio__layout"><Panel title="Surface registry"><div className="coverage-list">{filtered.map(item=><button type="button" key={item.id} className={selected===item.id?'coverage-row coverage-row--active':'coverage-row'} onClick={()=>setSelected(item.id)}><span className="coverage-icon"><Icon name={item.icon} size={12}/></span><span><strong>{item.label}</strong><small>{item.id} · {categoryLabel[item.group]}</small></span><Tag label={ownerOf(item.id)}/></button>)}{filtered.length===0&&<div className="coverage-empty">No surfaces match the current filter.</div>}</div></Panel>
 <Panel title={active.label}><div className="coverage-detail"><div><span className="eyebrow">{active.id}</span><h2>{active.label}</h2><p>{active.detail}</p></div><div className="coverage-facts"><div><span>UI owner</span><strong>{ownerOf(active.id)}</strong></div><div><span>Platform mode</span><strong>{platformModes.has(active.id)?'Yes':'Shell-owned'}</strong></div><div><span>Primary rail</span><strong>{primaryRailIds.has(active.id)?'Visible':'Secondary'}</strong></div><div><span>Runtime boundary</span><strong>Typed adapter</strong></div></div><div className="coverage-contract"><span className="eyebrow">Completion contract</span><div><Icon name="check-circle" size={13}/><span>Navigation metadata</span><Tag label="present"/></div><div><Icon name="check-circle" size={13}/><span>Surface owner</span><Tag label="present"/></div><div><Icon name="check-circle" size={13}/><span>Runtime effects</span><Tag label={ownerOf(active.id)==='PlatformSurface'?'adapter pending':'existing shell path'}/></div><div><Icon name="check-circle" size={13}/><span>Verification gate</span><Tag label="required"/></div></div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>onAction('Open '+active.label+' implementation in preview')}>Open implementation</button><button className="studio-button" type="button" onClick={()=>onAction('Open QA coverage for '+active.label)}>QA coverage</button><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('Open runtime contract for '+active.label)}>Runtime contract</button></div></div></Panel></div>
 <Panel title="Architecture audit"><div className="coverage-audit"><div><strong>Platform modes</strong><span>{platformModes.size} registered platform modes</span><Tag label={platformModes.size===dedicated?'aligned':'expected subset'}/></div><div><strong>Primary rail</strong><span>{primaryRailIds.size} core navigation entries</span><Tag label="intentionally curated"/></div><div><strong>Legacy owner</strong><span>{studioOwned.size} explicit StudioSurface entries</span><Tag label="tracked"/></div><div><strong>App owner</strong><span>{appOwned.size} shell-owned entries</span><Tag label="tracked"/></div></div><div className="coverage-guard"><Icon name="shield" size={13}/><span>Coverage is structural. A registered surface is not treated as runtime-complete until its service adapter and fresh verification evidence exist.</span></div></Panel>
 </div>
}