import { useMemo, useState } from 'react'
import { MetricCard, Panel, Tag } from './PlatformPrimitives'
import Icon from '../../components/Icon'

type UiState='Loading'|'Ready'|'Empty'|'Error'|'Offline'|'Reconnecting'|'Stale'|'Permission denied'|'Approval required'
const stateInfo:Record<UiState,[string,string,string]>={Loading:['Skeletons, progress and non-blocking placeholders','Avoid layout shift and show what is loading','In progress'],Ready:['Interactive controls and current data','Primary productive state','Healthy'],Empty:['Explain why there is no data and what to do next','Provide a safe first action','Actionable'],Error:['Preserve user input and isolate the failed surface','Offer retry plus diagnostics','Recoverable'],Offline:['Show cached state and queueable actions','Never imply live connectivity','Degraded'],Reconnecting:['Show retry/backoff without duplicating writes','Keep controls idempotent','Transient'],Stale:['Identify age and refresh semantics','Never present stale data as current','Degraded'],'Permission denied':['Explain missing capability without leaking secrets','Point to authorization path','Blocked'],'Approval required':['Freeze the risky action and show exact requested scope','Make approval explicit','Blocked']}
const surfaces=['Command Center','Files & Editor','Agent Mission Control','Task Execution','Git Control Center','Knowledge Studio','Memory Studio','Providers & Models','Browser','Computer Use','MCP','Environment Lab','Session Replay','Evidence Inspector','Release Center','Security Center','Observability','Automations']
export function FrontendStateMatrix({onAction}:{onAction:(message:string)=>void}){
 const [state,setState]=useState<UiState>('Ready'),[surface,setSurface]=useState(surfaces[0]),[filter,setFilter]=useState('')
 const filtered=useMemo(()=>surfaces.filter(s=>s.toLowerCase().includes(filter.toLowerCase())),[filter])
 const info=stateInfo[state]
 const blockedActionState=state==='Permission denied'||state==='Approval required'
 return <div className="state-matrix"><header className="state-matrix__hero"><div><span className="eyebrow">Resilience contract</span><h1>Frontend State Matrix</h1><p>Standardize how every substantial workspace behaves across loading, failure, connectivity, permissions and approval states.</p></div><div className="state-matrix__actions"><Tag label="QA surface"/><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('State contract export staged in preview')}>Export contract</button></div></header>
 <div className="platform-metrics"><MetricCard label="Surfaces" value={String(surfaces.length)} sub="Critical UX inventory"/><MetricCard label="States" value="9" sub="Required where relevant"/><MetricCard label="Contracts" value="Complete" sub="Presentation policy"/><MetricCard label="Runtime effect" value="None" sub="Diagnostic preview only"/></div>
 <div className="state-matrix__layout"><Panel title="Workspace surfaces"><div className="state-search"><Icon name="search" size={12}/><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Find surface…" aria-label="Find surface"/></div><div className="state-surfaces">{filtered.map(item=><button type="button" key={item} aria-current={surface===item?'page':undefined} className={surface===item?'state-surface state-surface--active':'state-surface'} onClick={()=>setSurface(item)}><span>{item}</span><small>9-state coverage</small></button>)}</div></Panel>
 <Panel title={surface}><div className="state-picker">{(Object.keys(stateInfo) as UiState[]).map(item=><button type="button" aria-pressed={state===item} className={state===item?'studio-button studio-button--active':'studio-button'} key={item} onClick={()=>setState(item)}>{item}</button>)}</div><div className="state-preview" role="status" aria-live="polite"><div className={'state-preview__icon state-preview__icon--'+state.toLowerCase().replaceAll(' ','-')}><Icon name={state==='Error'||state==='Permission denied'?'alert':state==='Approval required'?'lock':state==='Offline'?'cloud':state==='Loading'||state==='Reconnecting'?'activity':'check-circle'} size={18}/></div><div><span className="eyebrow">{state}</span><h2>{info[2]}</h2><p>{info[0]}</p><small>{info[1]}</small></div></div><div className="state-actions">{['Primary action','Secondary action','Retry','Diagnostics'].map(action=>{ const disabled=blockedActionState&&(action==='Primary action'||action==='Retry'); return <button className="studio-button" type="button" key={action} disabled={disabled} onClick={()=>onAction(action+' for '+surface+' · '+state+' staged in preview')}>{disabled?'Blocked':action}</button>})}</div><div className="state-rules"><div><span>Data truth</span><strong>{state==='Ready'?'Current / connected':'Never imply a live state'}</strong></div><div><span>User input</span><strong>Preserve</strong></div><div><span>Retry</span><strong>{state==='Permission denied'||state==='Approval required'?'Blocked until state changes':'Idempotent'}</strong></div><div><span>Telemetry</span><strong>Diagnostic-safe</strong></div></div></Panel></div>
 <Panel title="State implementation rules"><div className="state-rule-grid">{(Object.entries(stateInfo) as [UiState,[string,string,string]][]).map(([name,data])=><div key={name}><strong>{name}</strong><span>{data[1]}</span><Tag label={data[2]}/></div>)}</div><div className="state-matrix__guard"><Icon name="shield" size={13}/><span>These are UX contracts. They do not claim that the runtime can currently produce each state.</span></div></Panel>
 </div>
}