import { useState } from 'react'
import Icon from '../../components/Icon'
import { MetricCard, Panel, Tag } from './PlatformPrimitives'

const branches=[['main','ahead 0 · behind 0','protected'],['feature/runtime-routing','ahead 12 · behind 2','active'],['feature/ui-polish','ahead 4 · behind 0','active']]
const changes=[['M','crates/presentation/api-server/src/lib.rs','+42 −11'],['M','frontend/src/navigation.ts','+8 −2'],['A','docs/architecture/BACKEND-ARCHITECTURE-MAP.md','+96 −0']]
const commits=[['c11faba','Backend runtime vertical slice','2h ago'],['cb9a808','Developer Workspace','18m ago'],['d27cda6','Knowledge Studio','31m ago']]
export function GitControlCenter({onAction}:{onAction:(m:string)=>void}){
 const [tab,setTab]=useState<'changes'|'branches'|'history'>('changes')
 return <div className="studio-shell">
  <header className="platform-header"><div><span className="eyebrow">Repository plane</span><h1>Git Control Center</h1><p>Manage branches, changes, commits, checkpoints and collaboration state from a single review surface.</p></div><div className="platform-header__actions"><Tag label="Preview" /><button className="studio-button" onClick={()=>onAction('New branch dialog staged in preview')}><Icon name="plus" size={14}/> New branch</button><button className="studio-button studio-button--active" onClick={()=>onAction('Commit dialog staged in preview')}>Commit</button></div></header>
  <div className="platform-metrics"><MetricCard label="Working tree" value="3" sub="2 modified · 1 added"/><MetricCard label="Branch" value="main" sub="protected"/><MetricCard label="Ahead / behind" value="0 / 0" sub="origin/main"/><MetricCard label="Checkpoints" value="7" sub="recoverable snapshots"/></div>
  <div className="git-toolbar"><button className="studio-button" onClick={()=>onAction('Pull staged in preview')}>Pull</button><button className="studio-button" onClick={()=>onAction('Push staged in preview')}>Push</button><button className="studio-button" onClick={()=>onAction('Fetch staged in preview')}>Fetch</button><button className="studio-button" onClick={()=>onAction('Stash staged in preview')}>Stash</button><button className="studio-button" onClick={()=>onAction('Conflict resolver opened in preview')}>Resolve conflicts</button></div>
  <div className="git-tabs">{(['changes','branches','history'] as const).map(t=><button className={tab===t?'knowledge-tab knowledge-tab--active':'knowledge-tab'} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div>
  {tab==='changes'&&<div className="git-grid"><Panel title="Changes"><div className="git-list">{changes.map(([kind,path,delta])=><button className="git-row" key={path} onClick={()=>onAction('Diff opened for '+path)}><b>{kind}</b><span>{path}</span><small>{delta}</small></button>)}</div><div className="platform-actions"><button className="studio-button" onClick={()=>onAction('Stage selected changes in preview')}>Stage selected</button><button className="studio-button studio-button--active" onClick={()=>onAction('Review all changes in preview')}>Review all</button></div></Panel><Panel title="Safety"><div className="strategy-stack"><div><span>Protected branch</span><strong>Enabled</strong></div><div><span>Pre-commit checks</span><strong>Required</strong></div><div><span>Destructive actions</span><strong>Approval required</strong></div><div><span>Rollback</span><strong>Checkpoint available</strong></div></div></Panel></div>}
  {tab==='branches'&&<Panel title="Branches"><div className="git-list">{branches.map(([name,status,kind])=><button className="git-row" key={name} onClick={()=>onAction('Branch '+name+' selected')}><Icon name="branch" size={14}/><span>{name}</span><small>{status} · {kind}</small></button>)}</div></Panel>}
  {tab==='history'&&<Panel title="Commit history"><div className="git-list">{commits.map(([sha,msg,time])=><button className="git-row" key={sha} onClick={()=>onAction('Commit '+sha+' opened in preview')}><code>{sha}</code><span>{msg}</span><small>{time}</small></button>)}</div></Panel>}
  <div className="git-footer"><span>Safe Git mode enabled</span><span>Repository actions remain preview-only until the Git backend is connected.</span></div>
 </div>
}