import React from 'react'
import { Panel, Shell, Toast } from './PlatformPrimitives'
const rows=[['Builder','Files','Read / Write','Workspace'],['Builder','Terminal','Preview only','Workspace'],['Reviewer','Files','Read only','Workspace'],['Researcher','Network','Request','Session'],['Release Bot','Artifacts','Create','Release']]
export function PermissionsMatrix({onAction}:{onAction:(message:string)=>void}) {
 const [filter,setFilter]=React.useState('')
 const visible=rows.filter(r=>r.join(' ').toLowerCase().includes(filter.toLowerCase()))
 return <Shell><header className="platform-header"><div><span className="eyebrow">Authorization model</span><h1>Permissions Matrix</h1><p>Make agent capabilities explicit by actor, resource, operation and scope. Runtime enforcement remains a backend responsibility.</p></div><span className="state-pill state-pill--completed">Fail-closed preview</span></header>
 <div className="platform-grid platform-grid--2"><Panel title="Permission model"><div className="strategy-stack"><div><span>Principal</span><strong>Agent / subagent</strong></div><div><span>Resource</span><strong>Tool / workspace / network</strong></div><div><span>Action</span><strong>Read / write / execute / request</strong></div><div><span>Scope</span><strong>Workspace → session → task</strong></div></div></Panel><Panel title="Controls"><input className="global-search" value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Filter permissions…" /><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>onAction('Permission diff opened in preview')}>Compare policy</button><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('Permission editor opened in preview')}>Edit matrix</button></div></Panel></div>
 <Panel title="Effective permissions"><div className="permission-table"><div className="permission-head"><span>Actor</span><span>Resource</span><span>Operation</span><span>Scope</span></div>{visible.map(r=><button type="button" className="permission-row" key={r.join('-')} onClick={()=>onAction(r.join(' · ')+' selected')}><span>{r[0]}</span><span>{r[1]}</span><span>{r[2]}</span><span>{r[3]}</span></button>)}</div></Panel><Toast message="" /></Shell>
}
