import { useMemo, useState } from 'react'
import Icon from '../../components/Icon'
import { MetricCard, Panel, Tag } from './PlatformPrimitives'

type Tab='diagnostics'|'tests'|'coverage'
type Severity='error'|'warning'|'info'
const findings:Array<[string,Severity,string,string,string]>=[
 ['TS-042','error','Type mismatch in ProviderRoute','ProviderStudio.tsx:184','2 downstream references'],
 ['TS-039','warning','Missing explicit return type','AgentMissionControl.tsx:42','1 file'],
 ['QA-018','warning','Focus return not verified','CommandPalette.tsx:92','Accessibility'],
 ['RUST-011','info','Unused feature flag detected','agenticos-kernel/src/lib.rs:71','Runtime'],
]
const tests:Array<[string,string,string,string]>=[
 ['frontend/navigation.spec','Navigation registry stays unique','42 / 42','passed'],
 ['frontend/surface-routing.spec','Every PlatformMode routes','83 / 83','passed'],
 ['frontend/interaction.spec','Critical controls respond','26 / 31','pending'],
 ['frontend/a11y.spec','Keyboard and semantics','18 / 24','pending'],
 ['runtime/provider.spec','Provider boundary contract','12 / 12','passed'],
]
const coverage=[['navigation.ts','92%','42 / 46'],['PlatformSurface.tsx','86%','103 / 120'],['AgentMissionControl.tsx','74%','37 / 50'],['TaskExecutionCenter.tsx','68%','29 / 43'],['KnowledgeStudio.tsx','61%','22 / 36']]

export function QualityWorkbench({onAction}:{onAction:(message:string)=>void}){
 const [tab,setTab]=useState<Tab>('diagnostics'),[severity,setSeverity]=useState<'all'|Severity>('all'),[selected,setSelected]=useState(findings[0][0]),[search,setSearch]=useState('')
 const visibleFindings=useMemo(()=>findings.filter(f=>(severity==='all'||f[1]===severity)&&f.join(' ').toLowerCase().includes(search.toLowerCase())),[severity,search])
 const current=findings.find(f=>f[0]===selected)??findings[0]
 const act=(m:string)=>onAction(m+' staged in preview')
 return <div className="quality-workbench">
  <header className="quality-workbench__hero"><div><span className="eyebrow">Engineering quality</span><h1>Quality Workbench</h1><p>One quality surface for diagnostics, tests, coverage, quick fixes and release evidence across the entire frontend.</p></div><div className="quality-workbench__actions"><Tag label="QA contract"/><button className="studio-button" type="button" onClick={()=>act('Run targeted checks')}><Icon name="play" size={13}/>Run checks</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Open test plan')}><Icon name="check" size={13}/>Test plan</button></div></header>
  <div className="platform-metrics"><MetricCard label="Diagnostics" value="2 errors" sub="2 warnings · 1 info"/><MetricCard label="Tests" value="98 / 111" sub="13 pending"/><MetricCard label="Coverage" value="79%" sub="Frontend preview"/><MetricCard label="Release blockers" value="2" sub="Evidence required"/></div>
  <div className="quality-workbench__tabs">{(['diagnostics','tests','coverage'] as const).map(t=><button key={t} type="button" className={tab===t?'quality-tab quality-tab--active':'quality-tab'} onClick={()=>setTab(t)}>{t}</button>)}</div>
  {tab==='diagnostics'&&<div className="quality-workbench__layout"><Panel title="Diagnostics"><div className="quality-search"><Icon name="search" size={12}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search findings…" aria-label="Search diagnostics"/></div><div className="quality-filters">{(['all','error','warning','info'] as const).map(item=><button type="button" key={item} className={severity===item?'studio-button studio-button--active':'studio-button'} onClick={()=>setSeverity(item)}>{item}</button>)}</div><div className="diagnostic-list">{visibleFindings.map(f=><button type="button" key={f[0]} className={selected===f[0]?'diagnostic-row diagnostic-row--active':'diagnostic-row'} onClick={()=>setSelected(f[0])}><span className={'diagnostic-severity diagnostic-severity--'+f[1]}>{f[1][0].toUpperCase()}</span><span><strong>{f[2]}</strong><small>{f[0]} · {f[3]}</small></span><Tag label={f[1]}/></button>)}</div></Panel><Panel title={current[0]}><div className="diagnostic-detail"><span className="eyebrow">{current[1]}</span><h2>{current[2]}</h2><p>{current[3]}</p><div className="diagnostic-facts"><div><span>Impact</span><strong>{current[4]}</strong></div><div><span>Owner</span><strong>QA / Builder</strong></div><div><span>Repro</span><strong>Deterministic</strong></div><div><span>Gate</span><strong>{current[1]==='error'?'Blocking':'Review'}</strong></div></div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>act('Open source location')}>Open source</button><button className="studio-button" type="button" onClick={()=>act('Explain finding')}>Explain</button><button className="studio-button" type="button" onClick={()=>act('Generate quick fix')}>Quick fix</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Add regression test')}>Regression test</button></div></div></Panel></div>}
  {tab==='tests'&&<Panel title="Test Explorer"><div className="test-list">{tests.map(t=><div key={t[0]}><span className={t[3]==='passed'?'test-icon test-icon--pass':'test-icon'}><Icon name={t[3]==='passed'?'check':'clock'} size={11}/></span><div><strong>{t[1]}</strong><small>{t[0]} · {t[2]} cases</small></div><Tag label={t[3]}/><button className="studio-button" type="button" onClick={()=>act('Run '+t[0])}>Run</button></div>)}</div><div className="test-summary"><div><span>Last run</span><strong>RUN-QA-042</strong></div><div><span>Duration</span><strong>4m 18s</strong></div><div><span>Failed</span><strong>0</strong></div><div><span>Pending</span><strong>13</strong></div></div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>act('Run failed tests')}>Run failed</button><button className="studio-button" type="button" onClick={()=>act('Run changed-file tests')}>Changed files</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Run complete suite')}>Full suite</button></div></Panel>}
  {tab==='coverage'&&<div className="quality-workbench__coverage"><Panel title="File coverage"><div className="coverage-list-rows">{coverage.map(c=><div key={c[0]}><span><strong>{c[0]}</strong><small>{c[2]} statements</small></span><b>{c[1]}</b><div className="coverage-bar"><i style={{width:c[1]}}/></div>)}</div></Panel><Panel title="Coverage contract"><div className="coverage-rules"><div><span>Target</span><strong>80%+</strong></div><div><span>Changed files</span><strong>90%+</strong></div><div><span>Critical paths</span><strong>100% required</strong></div><div><span>Evidence</span><strong>Report attached</strong></div></div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>act('Open coverage gaps')}>Coverage gaps</button><button className="studio-button studio-button--active" type="button" onClick={()=>act('Export coverage report')}>Export report</button></div></Panel></div>}
  <div className="quality-workbench__guard"><Icon name="shield" size={13}/><span>Diagnostic and test labels in this interface are illustrative preview data until real verification adapters populate them. Release Center must consume runtime evidence, not these placeholders.</span></div>
 </div>
}