import { useState } from 'react'
import Icon from '../../components/Icon'
import { Panel, Metric, Tag } from './PlatformPrimitives'
const tools=[['filesystem.read','Read workspace files','Read','Low','Workspace','Auto'],['filesystem.write','Modify workspace files','Write','High','Project','Confirm'],['shell.exec','Execute shell commands','Execute','Critical','Sandbox','Confirm'],['browser.navigate','Navigate web pages','Network','Medium','Browser','Confirm'],['git.commit','Create git commits','Write','High','Repository','Confirm'],['secrets.read','Resolve credentials','Secrets','Critical','Provider','Block']]
export function ToolPolicyStudio({onAction}:{onAction:(message:string)=>void}) {
 const [selected,setSelected]=useState(tools[0][0]); const [mode,setMode]=useState('All'); const [approval,setApproval]=useState(true)
 const current=tools.find(t=>t[0]===selected)??tools[0]
 const filtered=tools.filter(t=>mode==='All'||t[2]===mode)
 return <div className="tool-policy-studio"><div className="memory-toolbar"><div className="segmented-control">{['All','Read','Write','Execute','Network','Secrets'].map(v=><button type="button" key={v} className={mode===v?'is-active':''} onClick={()=>setMode(v)}>{v}</button>)}</div><button className="studio-button" type="button" onClick={()=>onAction('Tool profile created in preview')}><Icon name="plus" size={13}/> New profile</button></div>
 <div className="tool-policy-layout"><div className="tool-registry-list">{filtered.map(t=><button type="button" key={t[0]} className={selected===t[0]?'tool-registry-row tool-registry-row--active':'tool-registry-row'} onClick={()=>setSelected(t[0])}><Icon name="tool" size={14}/><div><strong>{t[0]}</strong><span>{t[1]}</span></div><Tag label={t[3]}/></button>)}</div><Panel title={current[0]}><p className="panel-subtitle">{current[1]}</p><div className="platform-grid platform-grid--2"><Metric label="Operation" value={current[2]}/><Metric label="Risk" value={current[3]}/><Metric label="Scope" value={current[4]}/><Metric label="Default" value={current[5]}/></div><div className="policy-rule-table">{[['Read','Allowed','Workspace only'],['Write','Approval','Changed files only'],['Network','Approval','Explicit domains'],['Secrets','Blocked','Never exposed to model']].map(r=><div key={r[0]}><span>{r[0]}</span><strong>{r[1]}</strong><small>{r[2]}</small></div>)}</div><div className="platform-actions"><button className={approval?'studio-button studio-button--active':'studio-button'} type="button" onClick={()=>setApproval(v=>!v)}><Icon name="lock" size={13}/> {approval?'Human approval required':'Auto allowed'}</button><button className="studio-button" type="button" onClick={()=>onAction('Scope editor opened in preview')}>Edit scope</button><button className="studio-button" type="button" onClick={()=>onAction('Tool test staged in preview')}><Icon name="play" size={13}/> Test tool</button></div></Panel></div>
 <div className="platform-grid platform-grid--2"><Panel title="Tool profiles"><div className="strategy-stack"><div><span>Read-only</span><strong>Files + search + browser</strong></div><div><span>Builder</span><strong>Read + write + tests</strong></div><div><span>Reviewer</span><strong>Read + diff + diagnostics</strong></div><div><span>Release</span><strong>Approval-gated writes</strong></div></div></Panel><Panel title="Fail-closed policy"><div className="callout"><Icon name="shield" size={14}/><span>Unknown tools, missing scopes and credential access remain blocked until a runtime policy engine authorizes them.</span></div></Panel></div></div>
}
export default ToolPolicyStudio
