import { useState } from 'react'
import Icon from '../../components/Icon'
import { MetricCard, Panel, Tag } from './PlatformPrimitives'

const viewports=[['Desktop','1440×900','Primary'],['Laptop','1280×800','Primary'],['Tablet','1024×768','Compact'],['Mobile','390×844','Narrow']]
const checks=[['Keyboard navigation','Tab order, focus return, shortcuts','Pass'],['Reduced motion','Animations respect system preference','Ready'],['Contrast','Text and interactive controls','Ready'],['Semantics','Landmarks, headings, buttons and labels','Pass'],['Responsive layout','No clipped or inaccessible controls','Ready'],['Error recovery','Retry does not lose user input','Ready']]
export function VisualAccessibilityLab({onAction}:{onAction:(message:string)=>void}){
 const [viewport,setViewport]=useState(viewports[0][0]),[selected,setSelected]=useState(checks[0][0]),[reduced,setReduced]=useState(false),[highContrast,setHighContrast]=useState(false)
 const check=checks.find(c=>c[0]===selected)??checks[0]
 return <div className="visual-a11y"><header className="visual-a11y__hero"><div><span className="eyebrow">Quality verification</span><h1>Visual & Accessibility Lab</h1><p>Exercise the frontend contract across viewport, keyboard, motion, contrast, semantics and recovery scenarios before declaring a surface ready.</p></div><div className="visual-a11y__actions"><Tag label="Evidence required"/><button className={reduced?'studio-button studio-button--active':'studio-button'} type="button" onClick={()=>setReduced(v=>!v)}>Reduced motion</button><button className={highContrast?'studio-button studio-button--active':'studio-button'} type="button" onClick={()=>setHighContrast(v=>!v)}>High contrast</button></div></header>
 <div className="platform-metrics"><MetricCard label="Viewports" value="4" sub="Desktop → mobile"/><MetricCard label="Checks" value="6" sub="Accessibility + visual"/><MetricCard label="Evidence" value="0/6" sub="Not verified yet"/><MetricCard label="Release gate" value="Blocked" sub="Until evidence exists"/></div>
 <div className="visual-a11y__layout"><Panel title="Viewport matrix"><div className="viewport-grid">{viewports.map(v=><button type="button" key={v[0]} className={viewport===v[0]?'viewport-card viewport-card--active':'viewport-card'} onClick={()=>setViewport(v[0])}><strong>{v[0]}</strong><span>{v[1]}</span><small>{v[2]}</small></button>)}</div><div className="mock-preview"><div className="mock-preview__bar"><span>AgentiCOS · {viewport}</span><Tag label={reduced?'reduced-motion':'standard-motion'}/></div><div className={'mock-preview__canvas '+(highContrast?'mock-preview__canvas--contrast':'')}><div><span className="eyebrow">Preview frame</span><h2>Agent workspace</h2><p>Example visual verification frame for the selected viewport.</p><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('Visual interaction check staged in preview')}>Interact</button></div></div></div></Panel>
 <Panel title="Verification checklist"><div className="a11y-checks">{checks.map(c=><button type="button" key={c[0]} className={selected===c[0]?'a11y-row a11y-row--active':'a11y-row'} onClick={()=>setSelected(c[0])}><span className="a11y-row__dot"><Icon name={c[2]==='Pass'?'check':'clock'} size={11}/></span><span><strong>{c[0]}</strong><small>{c[1]}</small></span><Tag label={c[2]}/></button>)}</div><div className="a11y-detail"><span className="eyebrow">{check[0]}</span><h3>{check[2]}</h3><p>{check[1]}</p><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>onAction('Run '+check[0]+' check in preview')}>Run check</button><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('Capture '+check[0]+' evidence in preview')}><Icon name="archive" size={12}/>Capture evidence</button></div></div></Panel></div>
 <Panel title="Release evidence contract"><div className="visual-a11y__evidence">{['Screenshot set','Keyboard trace','Contrast report','Console capture','Responsive matrix','Recovery trace'].map(item=><div key={item}><Icon name="check-circle" size={13}/><span>{item}</span><small>Not verified</small></div>)}</div><div className="visual-a11y__guard"><Icon name="shield" size={13}/><span>Passing labels in this lab are UI expectations, not live test results. Release Center should remain blocked until real evidence is attached.</span></div></Panel>
 </div>
}