import { useState } from 'react'
import Icon from '../../components/Icon'
import { Panel, Metric, Tag } from './PlatformPrimitives'
const nodes=[['trigger','Start','Trigger'],['planner','Planner','Agent'],['research','Research','Subagent'],['builder','Builder','Agent'],['verify','Verify','Gate'],['approval','Human approval','Approval'],['release','Release','Action']]
export function WorkflowStudio({onAction}:{onAction:(message:string)=>void}) {
 const [selected,setSelected]=useState('planner'); const [mode,setMode]=useState('Design')
 const current=nodes.find(n=>n[0]===selected)??nodes[0]
 return <div className="workflow-studio"><div className="memory-toolbar"><div className="segmented-control">{['Design','Runs','Variables','Versions'].map(v=><button type="button" key={v} className={mode===v?'is-active':''} onClick={()=>setMode(v)}>{v}</button>)}</div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>onAction('Workflow validated in preview')}><Icon name="check" size={13}/> Validate</button><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('Workflow run staged in preview')}><Icon name="play" size={13}/> Test run</button></div></div>
 <div className="workflow-layout"><Panel title="Workflow graph"><div className="workflow-canvas">{nodes.map((n,i)=><div key={n[0]}><button type="button" className={selected===n[0]?'workflow-node workflow-node--active':'workflow-node'} onClick={()=>setSelected(n[0])}><span>{String(i+1).padStart(2,'0')}</span><strong>{n[1]}</strong><Tag label={n[2]}/></button>{i<nodes.length-1&&<div className="workflow-connector"><i/></div>}</div>)}</div><div className="workflow-add-row"><button className="studio-button" type="button" onClick={()=>onAction('Node picker opened in preview')}><Icon name="plus" size={13}/> Add node</button><button className="studio-button" type="button" onClick={()=>onAction('Parallel branch opened in preview')}>Parallel branch</button><button className="studio-button" type="button" onClick={()=>onAction('Condition builder opened in preview')}>Condition</button></div></Panel>
 <Panel title={current[1]}><span className="eyebrow">{current[2]} node</span><div className="platform-grid platform-grid--2"><Metric label="Timeout" value="10m"/><Metric label="Retries" value="2"/><Metric label="Context" value="Isolated"/><Metric label="On failure" value="Checkpoint"/></div><div className="workflow-config"><label>Execution policy<select className="settings-input" defaultValue="Bounded"><option>Bounded</option><option>Approval required</option><option>Read-only</option></select></label><label>Input mapping<textarea defaultValue={'task.title → objective\nfiles → workspace.files\nprevious.output → context'} /></label></div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>onAction('Node duplicated in preview')}><Icon name="copy" size={13}/> Duplicate</button><button className="studio-button" type="button" onClick={()=>onAction('Node test opened in preview')}>Test node</button><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('Node configuration saved in preview')}>Save node</button></div></Panel></div>
 <div className="platform-grid platform-grid--2"><Panel title="Workflow safeguards"><div className="strategy-stack"><div><span>Cycles</span><strong>Explicit loop budget</strong></div><div><span>Parallelism</span><strong>Bounded concurrency</strong></div><div><span>Human gates</span><strong>Required for release</strong></div><div><span>Recovery</span><strong>Checkpoint + retry</strong></div></div></Panel><Panel title="Variables & outputs"><div className="policy-rule-table"><div><span>objective</span><strong>string</strong><small>required</small></div><div><span>workspace</span><strong>scope</strong><small>read/write policy</small></div><div><span>artifacts</span><strong>list</strong><small>persisted outputs</small></div></div></Panel></div></div>
}
export default WorkflowStudio
