import { useEffect, useMemo, useState, type ReactNode } from 'react'
import Icon from '../../components/Icon'
import { runtime } from '../../services/runtime'
import { credentials as catalog } from '../platform/platformData'

type Credential={id:string;name:string;type:string;state:'Configured'|'Not configured';scope:string;provider:string;lastVerified:string;expires:string;secretKind:string}
const initial:Credential[]=catalog.map(([name,type,state,detail],i)=>({id:'cred-'+i,name,type,state:state==='Configured'?'Configured':'Not configured',scope:i===0?'Global':i===1?'Workspace':'Project',provider:name,lastVerified:i<2?'Today · preview':'Never',expires:i===0?'Not disclosed':i===1?'External policy':'Not configured',secretKind:detail}))

export default function CredentialManager({onAction}:{onAction:(message:string)=>void}){
 const [items,setItems]=useState(initial);const [selectedId,setSelectedId]=useState(initial[0].id);const [query,setQuery]=useState('');const [tab,setTab]=useState<'Overview'|'Scopes'|'Usage'>('Overview');const [showMeta,setShowMeta]=useState(true);const [runtimeSyncing,setRuntimeSyncing]=useState(true)
 const [usage,setUsage]=useState<{requests:number;tokens:number;requestsLimit?:number;tokensLimit?:number;failoverRoutes:number;autoFailover:boolean;events:Array<{event_id?:string;timestamp?:number;action?:string;resource?:string;outcome?:string}>} | null>(null)
 const [usageSyncing,setUsageSyncing]=useState(false)
 useEffect(()=>{let cancelled=false;void runtime.providers.list().then(providers=>{if(cancelled||providers.length===0)return;const mapped:Credential[]=providers.map(item=>({id:item.provider_id,name:item.name,type:item.name.toLowerCase().includes('local')?'Local provider':'API provider',state:item.configured?'Configured':'Not configured',scope:'Global',provider:item.name,lastVerified:item.health==='Healthy'?'Runtime healthy':'Needs verification',expires:item.configured?'Managed by runtime':'Not configured',secretKind:item.configured?'Credential configured':'Credential missing'}));setItems(mapped);setSelectedId(current=>mapped.some(item=>item.id===current)?current:mapped[0].id)}).catch(()=>{}).finally(()=>{if(!cancelled)setRuntimeSyncing(false)});return()=>{cancelled=true}},[])
 const current=items.find(i=>i.id===selectedId)??items[0]
 useEffect(()=>{if(tab!=='Usage'||!current)return;let cancelled=false;setUsageSyncing(true);void Promise.allSettled([runtime.providers.quota(current.id),runtime.providers.fallback(current.id),runtime.audit.list(20)]).then(([quotaResult,fallbackResult,auditResult])=>{if(cancelled)return;const quota=quotaResult.status==='fulfilled'?quotaResult.value:undefined;const fallback=fallbackResult.status==='fulfilled'?fallbackResult.value:undefined;const events=auditResult.status==='fulfilled'?auditResult.value.filter(event=>{const resource=typeof event.resource==='string'?event.resource:'';return !resource||resource.includes(current.id)}).slice(0,6).map(event=>({event_id:typeof event.event_id==='string'?event.event_id:undefined,timestamp:typeof event.timestamp==='number'?event.timestamp:undefined,action:typeof event.action==='string'?event.action:undefined,resource:typeof event.resource==='string'?event.resource:undefined,outcome:typeof event.outcome==='string'?event.outcome:undefined})):[];setUsage({requests:quota?.current_usage??0,tokens:quota?.current_token_usage??0,requestsLimit:quota?.requests_per_minute??undefined,tokensLimit:quota?.tokens_per_minute??undefined,failoverRoutes:Array.isArray(fallback?.fallback_providers)?fallback.fallback_providers.length:0,autoFailover:fallback?.auto_failover??false,events})}).finally(()=>{if(!cancelled)setUsageSyncing(false)});return()=>{cancelled=true}},[current?.id,tab])
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?items.filter(i=>[i.name,i.type,i.scope,i.provider,i.state].join(' ').toLowerCase().includes(q)):items},[items,query])
 return <div className="credential-manager">
  <aside className="credential-manager__rail"><div className="credential-manager__head"><div><span className="eyebrow">Secret boundary</span><strong>Credentials</strong></div><button className="icon-button" type="button" title="Add credential" aria-label="Add credential" onClick={()=>onAction('Credential creation is managed through provider registration')}><Icon name="plus" size={15}/></button></div><div className="credential-manager__search"><Icon name="search" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search connections…"/></div><div className="credential-manager__list">{visible.map(item=><button type="button" key={item.id} className={item.id===current.id?'credential-manager__item credential-manager__item--active':'credential-manager__item'} onClick={()=>setSelectedId(item.id)}><span className="credential-manager__icon"><Icon name="lock" size={14}/></span><span><strong>{item.name}</strong><small>{item.type} · {item.scope}</small></span><span className={item.state==='Configured'?'status-dot status-dot--live':'status-dot status-dot--offline'}/></button>)}</div><div className="credential-manager__foot"><span className="mono-text">{items.filter(i=>i.state==='Configured').length}/{items.length} configured</span><span className="state-pill state-pill--pending">{runtimeSyncing?'Syncing runtime':'Never reveal'}</span></div></aside>
  <section className="credential-manager__workspace"><header className="credential-manager__header"><div><span className="eyebrow">{current.state} · {current.scope} scope</span><h2>{current.name}</h2><p>{current.type} · credentials stay outside the React presentation state. {runtimeSyncing?'Synchronizing safe metadata.':'Runtime metadata loaded.'}</p></div><div className="credential-manager__actions"><button className={showMeta?'studio-button studio-button--active':'studio-button'} type="button" onClick={()=>setShowMeta(v=>!v)}><Icon name="lock" size={13}/> {showMeta?'Safe metadata':'Hide metadata'}</button><button className="studio-button" type="button" onClick={async()=>{try{const health=await runtime.providers.health(current.id);onAction(current.name+' health: '+health.status);setItems(list=>list.map(item=>item.id===current.id?{...item,lastVerified:'Just checked · runtime',state:health.status==='Healthy'?'Configured':item.state}:item))}catch(error){onAction(error instanceof Error?error.message:'Credential verification failed')}}}><Icon name="check-circle" size={13}/> Verify</button></div></header>
  <nav className="credential-manager__tabs" role="tablist" aria-label="Credential details">{(['Overview','Scopes','Usage'] as const).map(item=><button type="button" key={item} role="tab" aria-selected={tab===item} className={tab===item?'credential-manager__tab credential-manager__tab--active':'credential-manager__tab'} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  <div className="credential-manager__content">
   {tab==='Overview'&&<Section title="Connection overview" description="Inspect the safe metadata required to route an agent without exposing secret material."><div className="credential-manager__stat-grid"><Stat label="Provider" value={current.provider}/><Stat label="Type" value={current.type}/><Stat label="State" value={current.state}/><Stat label="Scope" value={current.scope}/><Stat label="Last verified" value={current.lastVerified}/><Stat label="Expires" value={showMeta?current.expires:'Hidden'}/></div><div className="credential-manager__secret"><div><span className="eyebrow">Secret value</span><strong>••••••••••••••••</strong><small>{showMeta?'Stored outside presentation state':'Metadata hidden'}</small></div><Icon name="lock" size={17}/></div><div className="callout"><Icon name="shield" size={14}/><span>API keys, OAuth tokens and session secrets never enter this component. Only readiness metadata is displayed.</span></div></Section>}
   {tab==='Scopes'&&<Section title="Scope & access" description="Scopes are currently derived from runtime provider registration and are not editable from the credential viewer."><div className="credential-manager__scope-list">{['Global','Project','Session'].map(scope=><div key={scope} className={current.scope===scope?'credential-manager__scope-row credential-manager__scope-row--active':'credential-manager__scope-row'}><div><strong>{scope}</strong><small>{scope==='Global'?'Available across configured workspaces':scope==='Project'?'Restricted to selected project':'Ephemeral session reference'}</small></div><span>{current.scope===scope?'Selected':'Available'}</span></div>)}</div><div className="callout"><Icon name="shield" size={14}/><span>Scope changes must go through the provider registration/runtime policy boundary; this view never writes secret or authorization state.</span></div></Section>}
   {tab==='Usage'&&<Section title="Usage & audit" description="Live quota, failover and audit metadata from the runtime; secret material remains excluded."><div className="credential-manager__usage-grid"><Stat label="Requests used" value={usageSyncing?'Syncing…':String(usage?.requests??0)}/><Stat label="Tokens used" value={usageSyncing?'Syncing…':String(usage?.tokens??0)}/><Stat label="Requests / min" value={usage?.requestsLimit!==undefined?String(usage.requestsLimit):'Unbounded'}/><Stat label="Failover routes" value={usage ? String(usage.failoverRoutes) : '—'}/></div><div className="credential-manager__audit"><div><span>01</span><strong>{usage?.autoFailover?'Automatic failover enabled':'Automatic failover disabled'}</strong><small>{usageSyncing?'Reading runtime policy':'Runtime routing policy'}</small></div>{usage?.events.length ? usage.events.map((event,index)=><div key={event.event_id??index}><span>{String(index+2).padStart(2,'0')}</span><strong>{event.action??'Runtime event'}</strong><small>{[event.outcome,event.resource].filter(Boolean).join(' · ') || 'Audit event'}</small></div>) : <div><span>02</span><strong>{usageSyncing?'Loading audit events':'No matching provider audit events'}</strong><small>Runtime audit</small></div>}</div></Section>}
  </div></section>
 </div>
}
function Section({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="credential-manager__section"><header><span className="eyebrow">Credential center</span><h3>{title}</h3><p>{description}</p></header><div className="credential-manager__section-body">{children}</div></section>}
function Stat({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}