import { useMemo, useState, type ReactNode } from 'react'
import Icon from '../../components/Icon'
import { researchBatches } from '../platform/platformData'

type Batch={id:string;title:string;inputs:number;state:'Running'|'Complete'|'Draft';sources:number;workers:number;mode:string;query:string;exportFormat:string}
const initial:Batch[]=researchBatches.map(([id,title,inputs,state],i)=>({id,title,inputs:Number.parseInt(inputs,10)||12,state:(state==='Complete'?'Complete':i===0?'Running':'Draft') as Batch['state'],sources:[128,84,42,16][i]??24,workers:[6,4,3,2][i]??2,mode:i===0?'Evidence first':'Compare',query:'Frontend agent architecture and current implementation evidence',exportFormat:'Markdown + JSON'}))

export default function ResearchWorkbench({onAction}:{onAction:(message:string)=>void}){
 const [items,setItems]=useState(initial);const [selectedId,setSelectedId]=useState(initial[0].id);const [tab,setTab]=useState<'Batch'|'Sources'|'Trajectories'|'Synthesis'>('Batch');const [query,setQuery]=useState('');const current=items.find(i=>i.id===selectedId)??items[0]
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?items.filter(i=>[i.id,i.title,i.query,i.mode].join(' ').toLowerCase().includes(q)):items},[items,query]);const patch=(v:Partial<Batch>)=>setItems(list=>list.map(i=>i.id===current.id?{...i,...v}:i))
 const create=()=>{const id='RES-'+(items.length+18);const next:Batch={...initial[0],id,title:'New research batch',state:'Draft',sources:0,workers:2,query:'Define research question',};setItems(l=>[next,...l]);setSelectedId(id);setTab('Batch');onAction('New research batch created in preview')}
 return <div className="research-workbench">
  <aside className="research-workbench__rail"><div className="research-workbench__head"><div><span className="eyebrow">Evidence operations</span><strong>Research</strong></div><button className="icon-button" type="button" title="New batch" aria-label="New batch" onClick={create}><Icon name="plus" size={15}/></button></div><div className="research-workbench__search"><Icon name="search" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search batches…"/></div><div className="research-workbench__list">{visible.map(item=><button type="button" key={item.id} className={item.id===current.id?'research-workbench__item research-workbench__item--active':'research-workbench__item'} onClick={()=>setSelectedId(item.id)}><span className="research-workbench__icon"><Icon name="archive" size={14}/></span><span><strong>{item.id} · {item.title}</strong><small>{item.sources} sources · {item.workers} workers</small></span><span className={item.state==='Running'?'status-dot status-dot--live':'status-dot status-dot--offline'}/></button>)}</div><div className="research-workbench__foot"><span className="mono-text">{items.length} batches</span><span className="state-pill state-pill--pending">Preview</span></div></aside>
  <section className="research-workbench__workspace"><header className="research-workbench__header"><div><span className="eyebrow">{current.state} · {current.mode}</span><h2>{current.id}</h2><p>{current.title} · {current.query}</p></div><div className="research-workbench__actions"><button className="studio-button" type="button" onClick={()=>onAction(current.id+' trajectory export staged in preview')}><Icon name="download" size={13}/> Export</button><button className="studio-button studio-button--active" type="button" onClick={()=>onAction(current.id+' research run staged in preview')}><Icon name="play" size={13}/> Run batch</button></div></header>
  <nav className="research-workbench__tabs" role="tablist" aria-label="Research workbench">{(['Batch','Sources','Trajectories','Synthesis'] as const).map(item=><button type="button" key={item} role="tab" aria-selected={tab===item} className={tab===item?'research-workbench__tab research-workbench__tab--active':'research-workbench__tab'} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  <div className="research-workbench__content">
   {tab==='Batch'&&<Section title="Research batch" description="Define the question, collection strategy, workers and export format for a bounded research job."><Field label="Research question"><textarea value={current.query} onChange={e=>patch({query:e.target.value})} rows={5}/></Field><div className="research-workbench__grid"><Field label="Research mode"><Select value={current.mode} options={['Evidence first','Compare','Explore','Audit']} onChange={value=>patch({mode:value})}/></Field><Field label="Workers"><Select value={String(current.workers)} options={['1','2','4','6','8']} onChange={value=>patch({workers:Number(value)})}/></Field><Field label="Export"><Select value={current.exportFormat} options={['Markdown + JSON','JSONL','Markdown','CSV']} onChange={value=>patch({exportFormat:value})}/></Field></div><div className="research-workbench__stat-grid"><Stat label="Inputs" value={String(current.inputs)}/><Stat label="Workers" value={String(current.workers)}/><Stat label="Sources" value={String(current.sources)}/><Stat label="State" value={current.state}/></div></Section>}
   {tab==='Sources'&&<Section title="Source ledger" description="Track source provenance, evidence quality and inclusion in the final synthesis."><div className="research-workbench__source-list">{['Official documentation','GitHub repository','Technical specification','Community discussion','Independent analysis'].map((name,i)=><div key={name}><span>{'0'+(i+1)}</span><div><strong>{name}</strong><small>{i===0?'Primary source':'Secondary source'} · {(current.sources/5+i).toFixed(0)} references</small></div><span className="state-pill state-pill--completed">Included</span></div>)}</div><div className="research-workbench__evidence"><div><span>Source quality</span><strong>High</strong></div><div><span>Primary ratio</span><strong>62%</strong></div><div><span>Conflicts</span><strong>3</strong></div><div><span>Unresolved</span><strong>1</strong></div></div></Section>}
   {tab==='Trajectories'&&<Section title="Research trajectories" description="Inspect parallel worker paths and where their evidence converges or diverges."><div className="research-workbench__trajectory-list">{['Discovery','Source verification','Cross-source comparison','Counterclaim check','Synthesis preparation'].map((step,i)=><div key={step}><span>{String(i+1).padStart(2,'0')}</span><div><strong>{step}</strong><small>{i<3?'complete':i===3?'review':'queued'} · '+(i+2)+' evidence nodes</small></div><span className={i<3?'state-pill state-pill--completed':i===3?'state-pill state-pill--pending':'state-pill'}>{i<3?'Complete':i===3?'Review':'Queued'}</span></div>)}</div><div className="callout"><Icon name="branch" size={14}/><span>Parallel research trajectories stay inspectable; synthesis is presented as a separate stage rather than silently blending sources.</span></div></Section>}
   {tab==='Synthesis'&&<Section title="Synthesis & export" description="Assemble an evidence-backed answer and preserve provenance before export or handoff."><div className="research-workbench__synthesis"><div><span className="eyebrow">Synthesis preview</span><h4>Evidence summary</h4><p>Primary sources support the architectural claims; secondary sources add implementation context. Conflicting details remain explicitly marked for review.</p></div><div className="research-workbench__confidence"><strong>0.91</strong><span>grounding score</span></div></div><div className="research-workbench__claim-list">{['Architecture requirement','Implementation evidence','Trade-off','Open question'].map((claim,i)=><div key={claim}><Icon name={i===3?'alert':'check-circle'} size={13}/><span>{claim}</span><small>{i===3?'Needs review':'Supported by ledger'}</small></div>)}</div><div className="platform-actions"><button className="studio-button" type="button" onClick={()=>onAction('Synthesis editor opened in preview')}>Edit synthesis</button><button className="studio-button studio-button--active" type="button" onClick={()=>onAction('Research evidence package exported in preview')}><Icon name="download" size={13}/> Export evidence package</button></div></Section>}
  </div></section>
 </div>
}
function Section({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="research-workbench__section"><header><span className="eyebrow">Research configuration</span><h3>{title}</h3><p>{description}</p></header><div className="research-workbench__section-body">{children}</div></section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="research-workbench__field"><span>{label}</span>{children}</label>}
function Select({value,options,onChange}:{value:string;options:string[];onChange:(value:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select>}
function Stat({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}