import { useMemo, useState, type ReactNode } from 'react'
import Icon from '../../components/Icon'
import { hooks as hookCatalog } from '../platform/platformData'

type HookEvent = 'Before run' | 'Before tool' | 'After tool' | 'On error' | 'After run'
type FailureMode = 'Fail closed' | 'Continue' | 'Retry bounded'
type Hook = { id:string; name:string; detail:string; group:string; enabled:boolean; event:HookEvent; order:number; matcher:string; action:string; failure:FailureMode; timeout:number; dryRun:boolean }

const events: HookEvent[] = ['Before run','Before tool','After tool','On error','After run']
const initialHooks: Hook[] = hookCatalog.map(([name, detail, group, enabled], index) => ({ id:name, name, detail, group, enabled, event:events[index] ?? 'After run', order:index+1, matcher:index===1 ? 'risk >= medium' : index===3 ? 'error != null' : 'always', action:index===0 ? 'Validate policy + approvals' : index===1 ? 'Evaluate tool allowlist' : index===2 ? 'Record outcome + artifacts' : index===3 ? 'Capture evidence + recovery' : 'Compile summary + handoff', failure:index===3 ? 'Retry bounded' : 'Fail closed', timeout:index===3 ? 5000 : 2500, dryRun:!enabled }))

export default function HookManager({ onAction }: { onAction:(message:string)=>void }) {
  const [items,setItems] = useState(initialHooks)
  const [selectedId,setSelectedId] = useState(initialHooks[0].id)
  const [query,setQuery] = useState('')
  const [tab,setTab] = useState<'Configuration'|'Trace'|'Test'>('Configuration')
  const current = items.find(item => item.id === selectedId) ?? items[0]
  const visible = useMemo(() => { const q=query.trim().toLowerCase(); return q ? items.filter(item => [item.name,item.detail,item.group,item.event,item.action].join(' ').toLowerCase().includes(q)) : items }, [items,query])
  function patch(value:Partial<Hook>){ setItems(list => list.map(item => item.id===current.id ? {...item,...value} : item)) }
  function addHook(){ const id='custom-hook-'+Date.now(); const next:Hook={...initialHooks[0],id,name:'custom-hook',detail:'New lifecycle policy hook',group:'Custom',enabled:false,order:items.length+1,event:'Before run',matcher:'always',action:'Describe the action to perform',failure:'Fail closed',timeout:2500,dryRun:true}; setItems(list=>[next,...list]); setSelectedId(id); setTab('Configuration'); onAction('New lifecycle hook created in preview') }
  return (
    <div className="hook-manager">
      <aside className="hook-manager__rail">
        <div className="hook-manager__rail-head"><div><span className="eyebrow">Lifecycle control</span><strong>Hooks</strong></div><button className="icon-button" type="button" title="Add hook" aria-label="Add hook" onClick={addHook}><Icon name="plus" size={15}/></button></div>
        <div className="hook-manager__search"><Icon name="search" size={14}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search hooks…"/></div>
        <div className="hook-manager__list">{visible.map(hook => <button type="button" key={hook.id} className={hook.id===current.id ? 'hook-manager__item hook-manager__item--active' : 'hook-manager__item'} onClick={()=>setSelectedId(hook.id)}><span className="hook-manager__item-icon"><Icon name={hook.enabled ? 'check-circle' : 'shield'} size={14}/></span><span><strong>{hook.name}</strong><small>{hook.event} · {hook.group}</small></span><span className={hook.enabled ? 'status-dot status-dot--live' : 'status-dot status-dot--offline'}/></button>)}</div>
        <div className="hook-manager__rail-foot"><span className="mono-text">{items.filter(item=>item.enabled).length}/{items.length} enabled</span><span className="state-pill state-pill--pending">Runtime-owned</span></div>
      </aside>
      <section className="hook-manager__workspace">
        <header className="hook-manager__header"><div><span className="eyebrow">{current.enabled ? 'Enabled' : 'Disabled'} · {current.event}</span><h2>{current.name}</h2><p>{current.detail} · {current.group}</p></div><div className="hook-manager__header-actions"><button className="studio-button" type="button" onClick={()=>onAction(current.name+' dry run started in preview')}><Icon name="play" size={13}/> Dry run</button><button className={current.enabled ? 'studio-button studio-button--active' : 'studio-button'} type="button" onClick={()=>patch({enabled:!current.enabled,dryRun:current.enabled})}><Icon name="check" size={13}/> {current.enabled ? 'Enabled' : 'Enable'}</button></div></header>
        <nav className="hook-manager__tabs" role="tablist" aria-label="Hook manager">{(['Configuration','Trace','Test'] as const).map(item=><button type="button" key={item} role="tab" aria-selected={tab===item} className={tab===item ? 'hook-manager__tab hook-manager__tab--active' : 'hook-manager__tab'} onClick={()=>setTab(item)}>{item}</button>)}</nav>
        <div className="hook-manager__content">
          {tab==='Configuration' && <Section title="Hook definition" description="Define when the lifecycle hook runs, what it matches, the action it performs and how failures are handled."><div className="hook-manager__grid hook-manager__grid--2"><Field label="Hook name"><input value={current.name} onChange={event=>patch({name:event.target.value||'untitled-hook'})}/></Field><Field label="Event"><Select value={current.event} options={events} onChange={value=>patch({event:value as HookEvent})}/></Field><Field label="Matcher"><input value={current.matcher} onChange={event=>patch({matcher:event.target.value})}/></Field><Field label="Order"><input type="number" min={1} max={100} value={current.order} onChange={event=>patch({order:Number(event.target.value)||1})}/></Field></div><Field label="Action"><textarea value={current.action} onChange={event=>patch({action:event.target.value})} rows={5}/></Field><div className="hook-manager__grid hook-manager__grid--3"><Field label="Failure behavior"><Select value={current.failure} options={['Fail closed','Continue','Retry bounded']} onChange={value=>patch({failure:value as FailureMode})}/></Field><Field label="Timeout"><input type="number" min={250} max={30000} step={250} value={current.timeout} onChange={event=>patch({timeout:Number(event.target.value)||250})}/></Field><Toggle label="Dry-run by default" value={current.dryRun} onChange={value=>patch({dryRun:value})}/></div><div className="hook-manager__order-preview"><div><span>Event</span><strong>{current.event}</strong></div><Icon name="chevron-right" size={15}/><div><span>Match</span><strong>{current.matcher}</strong></div><Icon name="chevron-right" size={15}/><div><span>Action</span><strong>{current.action}</strong></div></div><div className="callout"><Icon name="shield" size={14}/><span>Hook ordering and authorization are runtime concerns. This editor previews intended policy and never executes middleware in the browser.</span></div></Section>}
          {tab==='Trace' && <Section title="Lifecycle trace" description="Review where the hook sits in the execution lifecycle and what evidence it is expected to produce."><div className="hook-manager__trace">{[['01','Before run','Context + policy sealed'],['02','Before tool','Risk + allowlist evaluated'],['03','After tool','Outcome + artifact references'],['04','On error','Evidence + recovery path'],['05','After run','Summary + handoff package']].map(([index,title,detail],i)=>{ const active=current.event===events[i]; return <div className={active?'hook-manager__trace-row hook-manager__trace-row--active':'hook-manager__trace-row'} key={title}><span>{index}</span><div><strong>{title}</strong><small>{detail}</small></div><span>{active?'selected':'sequence'}</span></div> })}</div><div className="hook-manager__trace-evidence"><span className="eyebrow">Expected evidence</span><div><Tag label="policy result"/><Tag label="event id"/><Tag label="duration"/><Tag label="artifact refs"/><Tag label="error context"/></div></div></Section>}
          {tab==='Test' && <Section title="Hook test bench" description="Preview test payloads, expected outcomes and dry-run behavior without invoking runtime middleware."><div className="hook-manager__test-head"><div><span className="eyebrow">Fixture</span><strong>{current.event.toLowerCase().replaceAll(' ','_')}</strong><small>synthetic event payload</small></div><button className="studio-button studio-button--active" type="button" onClick={()=>onAction(current.name+' test fixture executed in preview')}><Icon name="play" size={13}/> Run fixture</button></div><pre className="hook-manager__payload">{JSON.stringify({event:current.event,hook:current.name,matcher:current.matcher,risk:'medium',dry_run:current.dryRun},null,2)}</pre><div className="hook-manager__test-result"><div><span>Expected</span><strong>{current.failure==='Fail closed'?'Gate action until policy passes':current.failure==='Retry bounded'?'Retry within limit':'Continue lifecycle'}</strong></div><span className="state-pill state-pill--completed">Fixture valid</span></div></Section>}
        </div>
      </section>
    </div>
  )
}

function Section({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="hook-manager__section"><header><span className="eyebrow">Hook configuration</span><h3>{title}</h3><p>{description}</p></header><div className="hook-manager__section-body">{children}</div></section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="hook-manager__field"><span>{label}</span>{children}</label>}
function Select({value,options,onChange}:{value:string;options:string[];onChange:(value:string)=>void}){return <select className="hook-manager__select" value={value} onChange={event=>onChange(event.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){return <button type="button" aria-pressed={value} className={value?'hook-manager__toggle hook-manager__toggle--active':'hook-manager__toggle'} onClick={()=>onChange(!value)}><span><strong>{label}</strong><small>{value?'Enabled':'Disabled'}</small></span><span className="switch"><span/></span></button>}
function Tag({label}:{label:string}){return <span className="platform-tag">{label}</span>}