import { useMemo, useState, type ReactNode } from 'react'
import Icon from '../../components/Icon'
import { channels } from '../platform/platformData'

type Channel={id:string;name:string;type:string;state:'Connected'|'Ready'|'Paused';detail:string;mode:string;threading:boolean;attachments:boolean;voice:boolean;delivery:string}
const initial:Channel[]=channels.map(([name,type,state,detail],i)=>({id:'channel-'+i,name,type,state:(state==='Connected'?'Connected':i===1?'Paused':'Ready') as Channel['state'],detail,mode:i===0?'Interactive':'Relay',threading:i<3,attachments:i!==2,voice:i===0,delivery:'Workspace inbox'}))

export default function ChannelGatewayManager({onAction}:{onAction:(message:string)=>void}){
 const [items,setItems]=useState(initial);const [selectedId,setSelectedId]=useState(initial[0].id);const [tab,setTab]=useState<'Channels'|'Gateway'|'Delivery'|'Sessions'>('Channels');const [query,setQuery]=useState('')
 const current=items.find(i=>i.id===selectedId)??items[0]
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?items.filter(i=>[i.name,i.type,i.detail,i.mode].join(' ').toLowerCase().includes(q)):items},[items,query])
 const patch=(v:Partial<Channel>)=>setItems(list=>list.map(i=>i.id===current.id?{...i,...v}:i))
 return <div className="channel-gateway-manager">
  <aside className="channel-gateway-manager__rail"><div className="channel-gateway-manager__head"><div><span className="eyebrow">Gateway plane</span><strong>Channels</strong></div><button className="icon-button" type="button" title="Add channel" aria-label="Add channel" onClick={()=>onAction('Channel setup opened in preview')}><Icon name="plus" size={15}/></button></div><div className="channel-gateway-manager__search"><Icon name="search" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search channels…"/></div><div className="channel-gateway-manager__list">{visible.map(item=><button type="button" key={item.id} className={item.id===current.id?'channel-gateway-manager__item channel-gateway-manager__item--active':'channel-gateway-manager__item'} onClick={()=>setSelectedId(item.id)}><span className="channel-gateway-manager__icon"><Icon name={item.name==='Desktop'?'layout':'message'} size={14}/></span><span><strong>{item.name}</strong><small>{item.type} · {item.mode}</small></span><span className={item.state==='Connected'?'status-dot status-dot--live':'status-dot status-dot--offline'}/></button>)}</div><div className="channel-gateway-manager__foot"><span className="mono-text">{items.filter(i=>i.state==='Connected').length}/{items.length} connected</span><span className="state-pill state-pill--pending">Runtime-owned</span></div></aside>
  <section className="channel-gateway-manager__workspace"><header className="channel-gateway-manager__header"><div><span className="eyebrow">{current.state} · {current.type}</span><h2>{current.name}</h2><p>{current.detail} · {current.mode} delivery</p></div><div className="channel-gateway-manager__actions"><button className="studio-button" type="button" onClick={()=>onAction(current.name+' connection test staged in preview')}><Icon name="check-circle" size={13}/> Test</button><button className="studio-button studio-button--active" type="button" onClick={()=>onAction(current.name+' configuration saved in preview')}><Icon name="check" size={13}/> Save</button></div></header>
  <nav className="channel-gateway-manager__tabs" role="tablist" aria-label="Gateway configuration">{(['Channels','Gateway','Delivery','Sessions'] as const).map(item=><button type="button" key={item} role="tab" aria-selected={tab===item} className={tab===item?'channel-gateway-manager__tab channel-gateway-manager__tab--active':'channel-gateway-manager__tab'} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  <div className="channel-gateway-manager__content">
   {tab==='Channels'&&<Section title="Channel capabilities" description="Choose which messaging features and conversation behavior the channel exposes to an agent session."><Toggle label="Thread continuity" value={current.threading} onChange={value=>patch({threading:value})}/><Toggle label="Attachments" value={current.attachments} onChange={value=>patch({attachments:value})}/><Toggle label="Voice messages" value={current.voice} onChange={value=>patch({voice:value})}/><Field label="Conversation mode"><Select value={current.mode} options={['Interactive','Relay','Broadcast','Notification']} onChange={value=>patch({mode:value})}/></Field><div className="channel-gateway-manager__cap-strip"><Tag label="sessions"/><Tag label="mentions"/><Tag label="attachments"/><Tag label="thread routing"/></div></Section>}
   {tab==='Gateway'&&<Section title="Gateway routing" description="Preview the gateway envelope that connects channels to sessions, agents and outbound delivery."><div className="channel-gateway-manager__route"><div><span>Inbound</span><strong>{current.name}</strong><small>channel adapter</small></div><Icon name="chevron-right" size={14}/><div><span>Gateway</span><strong>AgentiCOS</strong><small>session router</small></div><Icon name="chevron-right" size={14}/><div><span>Agent</span><strong>Builder</strong><small>active profile</small></div></div><div className="channel-gateway-manager__stat-grid"><Stat label="Session continuity" value="Strict"/><Stat label="Thread mode" value={current.threading?'Preserved':'Flat'}/><Stat label="Attachments" value={current.attachments?'Allowed':'Blocked'}/><Stat label="Human gate" value="Sensitive"/></div><div className="callout"><Icon name="shield" size={14}/><span>Gateway routing and authorization are runtime-owned; this view previews the intended envelope.</span></div></Section>}
   {tab==='Delivery'&&<Section title="Delivery policy" description="Define where results, failures and artifacts should appear for this channel."><Field label="Default destination"><Select value={current.delivery} options={['Workspace inbox','Thread reply','Direct message','Artifact only','Webhook']} onChange={value=>patch({delivery:value})}/></Field><Toggle label="Send completion events" value={true} onChange={()=>onAction('Completion delivery preference staged in preview')}/><Toggle label="Send failure alerts" value={true} onChange={()=>onAction('Failure delivery preference staged in preview')}/><Toggle label="Attach artifacts automatically" value={current.attachments} onChange={value=>patch({attachments:value})}/><div className="channel-gateway-manager__delivery"><span className="eyebrow">Delivery preview</span><strong>{current.delivery}</strong><small>Uses channel policy and current session permissions.</small></div></Section>}
   {tab==='Sessions'&&<Section title="Session routing" description="Inspect the logical sessions currently associated with the channel."><div className="channel-gateway-manager__session-list">{['Builder · RUN-042','Reviewer · RUN-041','Researcher · RES-018'].map((item,i)=><div key={item}><span>{'0'+(i+1)}</span><div><strong>{item}</strong><small>{i===0?'Active session':'Ready for handoff'}</small></div><span className={i===0?'status-dot status-dot--live':'status-dot status-dot--offline'}/></div>)}</div><button className="studio-button" type="button" onClick={()=>onAction('Session routing browser opened in preview')}><Icon name="users" size={13}/> Manage sessions</button></Section>}
  </div></section>
 </div>
}
function Section({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="channel-gateway-manager__section"><header><span className="eyebrow">Gateway configuration</span><h3>{title}</h3><p>{description}</p></header><div className="channel-gateway-manager__section-body">{children}</div></section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="channel-gateway-manager__field"><span>{label}</span>{children}</label>}
function Select({value,options,onChange}:{value:string;options:string[];onChange:(value:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){return <button type="button" className={value?'channel-gateway-manager__toggle channel-gateway-manager__toggle--active':'channel-gateway-manager__toggle'} aria-pressed={value} onClick={()=>onChange(!value)}><span><strong>{label}</strong><small>{value?'Enabled':'Disabled'}</small></span><span className="switch"><span/></span></button>}
function Tag({label}:{label:string}){return <span className="platform-tag">{label}</span>}
function Stat({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}