import { useMemo, useState, type ReactNode } from 'react'
import Icon from '../../components/Icon'
import { automations as catalog } from '../platform/platformData'

type Automation={id:string;name:string;description:string;schedule:string;trigger:string;agent:string;scope:string;delivery:string;concurrency:'1'|'2'|'4'|'8';timeout:number;enabled:boolean;nextRun:string}
const initial:Automation[]=catalog.map(([name,schedule,trigger,state],i)=>({id:'auto-'+i,name,description:'Recurring agent workflow with explicit trigger, policy and delivery.',schedule,trigger,agent:['Builder','Reviewer','Researcher','Release Bot'][i]??'Builder',scope:'Project',delivery:'Workspace notification',concurrency:i===1?'2':'1',timeout:30,enabled:state==='Enabled',nextRun:['in 2h','in 5h','Mon 09:00','on release'][i]??'scheduled'}))

export default function AutomationBuilder({onAction}:{onAction:(message:string)=>void}){
 const [items,setItems]=useState(initial);const [selectedId,setSelectedId]=useState(initial[0].id);const [tab,setTab]=useState<'Overview'|'Trigger'|'Execution'|'Delivery'>('Overview');const [query,setQuery]=useState('')
 const current=items.find(i=>i.id===selectedId)??items[0]
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?items.filter(i=>[i.name,i.description,i.schedule,i.trigger,i.agent].join(' ').toLowerCase().includes(q)):items},[items,query])
 const patch=(v:Partial<Automation>)=>setItems(list=>list.map(i=>i.id===current.id?{...i,...v}:i))
 const create=()=>{const id='auto-'+Date.now();const next:Automation={...initial[0],id,name:'New automation',description:'Define a recurring agent workflow.',enabled:false,nextRun:'Not scheduled'};setItems(l=>[next,...l]);setSelectedId(id);setTab('Overview');onAction('New automation created in preview')}
 return <div className="automation-builder">
  <aside className="automation-builder__rail"><div className="automation-builder__rail-head"><div><span className="eyebrow">Schedules & triggers</span><strong>Automations</strong></div><button className="icon-button" type="button" aria-label="Create automation" title="Create automation" onClick={create}><Icon name="plus" size={15}/></button></div><div className="automation-builder__search"><Icon name="search" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search automations…"/></div><div className="automation-builder__list">{visible.map(item=><button type="button" key={item.id} className={item.id===current.id?'automation-builder__item automation-builder__item--active':'automation-builder__item'} onClick={()=>setSelectedId(item.id)}><span className="automation-builder__icon"><Icon name="calendar" size={14}/></span><span><strong>{item.name}</strong><small>{item.agent} · {item.schedule}</small></span><span className={item.enabled?'status-dot status-dot--live':'status-dot status-dot--offline'}/></button>)}</div><div className="automation-builder__rail-foot"><span className="mono-text">{items.filter(i=>i.enabled).length}/{items.length} enabled</span><span className="state-pill state-pill--pending">Preview</span></div></aside>
  <section className="automation-builder__workspace"><header className="automation-builder__header"><div><span className="eyebrow">{current.enabled?'Enabled':'Paused'} · {current.scope}</span><h2>{current.name}</h2><p>{current.description}</p></div><div className="automation-builder__header-actions"><span className="state-pill state-pill--pending">Next: {current.nextRun}</span><button className="studio-button" type="button" onClick={()=>onAction(current.name+' dry run staged in preview')}><Icon name="play" size={13}/> Dry run</button><button className="studio-button studio-button--active" type="button" onClick={()=>patch({enabled:!current.enabled})}>{current.enabled?'Pause':'Enable'}</button></div></header>
  <nav className="automation-builder__tabs" role="tablist" aria-label="Automation builder">{(['Overview','Trigger','Execution','Delivery'] as const).map(item=><button type="button" key={item} role="tab" aria-selected={tab===item} className={tab===item?'automation-builder__tab automation-builder__tab--active':'automation-builder__tab'} onClick={()=>setTab(item)}>{item}</button>)}</nav>
  <div className="automation-builder__content">
   {tab==='Overview'&&<Section title="Automation overview" description="Define the reusable agent workflow and its operating scope."><div className="automation-builder__grid automation-builder__grid--2"><Field label="Name"><input value={current.name} onChange={e=>patch({name:e.target.value})}/></Field><Field label="Agent"><Select value={current.agent} options={['Builder','Reviewer','Researcher','Release Bot']} onChange={value=>patch({agent:value})}/></Field><Field label="Scope"><Select value={current.scope} options={['Global','Project','Workspace']} onChange={value=>patch({scope:value})}/></Field><Field label="Schedule"><input value={current.schedule} onChange={e=>patch({schedule:e.target.value})}/></Field></div><div className="automation-builder__stat-grid"><Stat label="Trigger" value={current.trigger}/><Stat label="Next run" value={current.nextRun}/><Stat label="Concurrency" value={current.concurrency}/><Stat label="Timeout" value={current.timeout+' min'}/></div></Section>}
   {tab==='Trigger'&&<Section title="Trigger & schedule" description="Combine cron-like schedules with repository, webhook or lifecycle triggers."><Field label="Natural-language schedule"><input value={current.schedule} onChange={e=>patch({schedule:e.target.value,nextRun:'Recomputed preview'})}/></Field><Field label="Trigger type"><Select value={current.trigger} options={['Cron','Git change trigger','Webhook','Release tag','Manual']} onChange={value=>patch({trigger:value})}/></Field><div className="automation-builder__schedule-preview"><div><span>Schedule</span><strong>{current.schedule}</strong></div><Icon name="chevron-right" size={14}/><div><span>Trigger</span><strong>{current.trigger}</strong></div><Icon name="chevron-right" size={14}/><div><span>Next execution</span><strong>{current.nextRun}</strong></div></div><div className="callout"><Icon name="info" size={14}/><span>Calendar computation and trigger delivery remain outside the frontend until runtime scheduling is connected.</span></div></Section>}
   {tab==='Execution'&&<Section title="Execution policy" description="Bound concurrency, timeout and context behavior for repeated runs."><Field label="Concurrency"><Select value={current.concurrency} options={['1','2','4','8']} onChange={value=>patch({concurrency:value as Automation['concurrency']})}/></Field><Range label="Timeout" value={current.timeout} min={5} max={120} suffix={current.timeout+' min'} onChange={value=>patch({timeout:value})}/><Toggle label="Use project context pack" value={true} onChange={()=>onAction('Context attachment preference staged in preview')}/><Toggle label="Require approval for sensitive actions" value={true} onChange={()=>onAction('Approval preference staged in preview')}/><div className="automation-builder__execution-strip"><Stat label="Agent" value={current.agent}/><Stat label="Context" value="Project pack"/><Stat label="Policy" value="Fail closed"/></div></Section>}
   {tab==='Delivery'&&<Section title="Results & delivery" description="Decide where completion, failure and artifacts should appear."><Field label="Delivery"><Select value={current.delivery} options={['Workspace notification','Channel delivery','Artifact only','Webhook']} onChange={value=>patch({delivery:value})}/></Field><Toggle label="Attach artifacts" value={true} onChange={()=>onAction('Artifact attachment preference staged in preview')}/><Toggle label="Notify on failure" value={true} onChange={()=>onAction('Failure notification preference staged in preview')}/><Toggle label="Include execution summary" value={true} onChange={()=>onAction('Summary preference staged in preview')}/><div className="automation-builder__delivery-card"><div><span className="eyebrow">Delivery preview</span><strong>{current.delivery}</strong><small>Success, failure and handoff events use the same workspace policy boundary.</small></div><span className="state-pill state-pill--completed">Ready</span></div></Section>}
  </div></section>
 </div>
}
function Section({title,description,children}:{title:string;description:string;children:ReactNode}){return <section className="automation-builder__section"><header><span className="eyebrow">Automation configuration</span><h3>{title}</h3><p>{description}</p></header><div className="automation-builder__section-body">{children}</div></section>}
function Field({label,children}:{label:string;children:ReactNode}){return <label className="automation-builder__field"><span>{label}</span>{children}</label>}
function Select({value,options,onChange}:{value:string;options:string[];onChange:(value:string)=>void}){return <select value={value} onChange={e=>onChange(e.target.value)}>{options.map(option=><option key={option}>{option}</option>)}</select>}
function Range({label,value,min,max,suffix,onChange}:{label:string;value:number;min:number;max:number;suffix:string;onChange:(value:number)=>void}){return <label className="automation-builder__range"><span><span>{label}</span><strong>{suffix}</strong></span><input type="range" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Toggle({label,value,onChange}:{label:string;value:boolean;onChange:(value:boolean)=>void}){return <button type="button" className={value?'automation-builder__toggle automation-builder__toggle--active':'automation-builder__toggle'} aria-pressed={value} onClick={()=>onChange(!value)}><span><strong>{label}</strong><small>{value?'Enabled':'Disabled'}</small></span><span className="switch"><span/></span></button>}
function Stat({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}